/**
 * THE PARITY PROOF — for the private-repository crypto core.
 *
 * Runs every `forge-contracts/vectors/private_*.json` (`docs/security/private-repos.md` §11,
 * generated by `tools/private-repos-vectors/gen.py`) against `lib/private`; the Rust
 * `forge-core::private` runs the same files. Each case has an allow-list of input keys at
 * every depth, so a vector cannot carry a field this harness would silently ignore.
 *
 * `private_kdf` expects raw subkey bytes that non-extractable WebCrypto keys cannot reveal, so
 * those are checked with @noble/hashes; KCV and COMMIT go through the production path, and
 * every other subkey is covered byte for byte by the doc, ref, pack and hedge vectors.
 */

import { readFileSync, readdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { expand } from '@noble/hashes/hkdf.js'
import { hmac } from '@noble/hashes/hmac.js'
import { sha256 as nobleSha256 } from '@noble/hashes/sha2.js'
import { beforeAll, describe, expect, it } from 'vitest'

import { bytesToHex, concat, hexToBytes, sha256 } from './bytes'
import { TooLargeError, openContent, type OpenContext, type OpenResult, type PrivateDoc, type StoredPrivateDoc } from './doc'
import {
  contentIsLate,
  manifestStanding,
  resolveEpochs,
  type ConfigRow,
  type PrivateMembership,
  type WrapRow,
} from './epoch'
import { EpochKeys, refNameHash, subkeyInfo, type EpochKeyring } from './keys'
import { PackError, PackHeaderCache, openPack, parseHeader, planRange, readPackRange, segmentCount } from './pack'
import { buildTlv, MalformedError, type DocFields, type PrivateDocType } from './tlv'
import { WrapError, buildWrapPlaintext, openWrap, sealWrap, type WrapFacade } from './wrap'
import { hedgedFileId, hedgedNonce, sealDocWithNonce, sealPackWithFileId } from './testing'
import { IdSet, encodePrivateId, privateId, type IdEncoding } from './ids'

type Evo = typeof import('@dashevo/evo-sdk')
type Json = null | boolean | number | string | Json[] | { [k: string]: Json }
type Obj = { readonly [k: string]: Json }

interface Vector {
  readonly name: string
  readonly description: string
  readonly case: string
  readonly rules: string
  readonly input: Obj
  readonly expected: Json
}

const ROOT = resolve(process.cwd(), '..')
const VECTORS_DIR = resolve(ROOT, 'forge-contracts', 'vectors')
/**
 * Sealed releases (`private-repos.md` §16) are specified but not implemented in the web app
 * yet: their vectors are checked by gen.py and forge-core's test-only reference, and this
 * harness takes them on with the web implementation (`lib/repo/releases.ts`), which removes
 * this filter.
 */
const NOT_YET_IMPLEMENTED = /^private_release_(seal|open)__/
const PRIVATE_FILES = readdirSync(VECTORS_DIR)
  .filter((f) => f.startsWith('private_') && f.endsWith('.json') && !NOT_YET_IMPLEMENTED.test(f))
  .sort()

// ---------------------------------------------------------------------------------------------
// Input allow-lists
// ---------------------------------------------------------------------------------------------

/** An input shape: a scalar (or scalar array), an array of shapes, a map of shapes, or exact keys. */
type Shape =
  | { readonly kind: 'leaf' }
  | { readonly kind: 'each'; readonly of: Shape }
  | { readonly kind: 'values'; readonly of: Shape }
  | { readonly kind: 'object'; readonly fields: { readonly [k: string]: Shape } }

const LEAF: Shape = { kind: 'leaf' }
const each = (of: Shape): Shape => ({ kind: 'each', of })
const values = (of: Shape): Shape => ({ kind: 'values', of })
const object = (fields: { readonly [k: string]: Shape }): Shape => ({ kind: 'object', fields })
const leafFields = (...keys: string[]) => Object.fromEntries(keys.map((k) => [k, LEAF]))
const leaves = (...keys: string[]): Shape => object(leafFields(...keys))

const DOC_KEYS = [
  'type', 'ownerId', 'epoch', 'number', 'targetId', 'patchId', 'refNameHash', 'newOid', 'prevOid',
  'force', 'baseRefNameHash', 'sourceRefNameHash',
]
const FIELDS = leaves(
  'title', 'body', 'refName', 'baseRefName', 'sourceRefName', 'defaultBranch', 'protectedPatterns',
  'prevEpoch', 'prevEpochKey', 'path', 'burned', 'skipEpochKey', 'importedAuthor', 'importedUrl', 'eventValue',
)
const KEY_INPUT = ['repoId', 'key', 'epoch']
const SEAL_PACK = leaves(...KEY_INPUT, 'fileId', 'plaintextMod251', 'plaintextHex')

const SHAPES: Readonly<Record<string, Shape>> = {
  private_kdf: leaves(...KEY_INPUT, 'fileId'),
  private_ref_hash: leaves(...KEY_INPUT, 'refName'),
  private_doc_seal: object({ ...leafFields('repoId', 'key', 'nonce', 'anchor'), doc: leaves(...DOC_KEYS), fields: FIELDS }),
  private_doc_open: object({
    repoId: LEAF,
    context: object({ keys: values(LEAF), anchors: values(leaves('id', 'height')), members: LEAF, burned: LEAF }),
    doc: leaves(...DOC_KEYS, 'id', 'createdAtBlockHeight', 'updatedAtBlockHeight', 'enc'),
  }),
  private_collab_seal: object({
    ...leafFields('repoId', 'key', 'epoch', 'ownerId', 'docType', 'nonce'),
    props: object({
      ...leafFields('number', 'title', 'body', 'baseRefName', 'baseRefNameHash', 'sourceRefName', 'sourceRefNameHash', 'sourceRepoId', 'headOid', 'patchManifestHash', 'draft', 'targetId', 'path', 'replyTo', 'reviewId', 'commitOid', 'line', 'startLine', 'side', 'patchId', 'verdict', 'commentCount', 'targetNumber', 'kind', 'value', 'refId'),
      imported: leaves('author', 'createdAt', 'url'),
    }),
  }),
  private_pack_seal: SEAL_PACK,
  private_pack_open: object({ ...leafFields('repoId', 'sealed', 'sizeBytes'), keys: values(LEAF) }),
  private_pack_range: object({ seal: SEAL_PACK, range: LEAF }),
  private_wrap_seal: leaves('repoId', 'senderPriv', 'senderPub', 'recipientPriv', 'recipientPub', 'key', 'epoch', 'iv'),
  private_wrap_open: leaves('repoId', 'epoch', 'wrapped', 'readerPriv', 'counterpartyPub', 'anchorCommit'),
  private_epoch: object({
    ...leafFields('repoId', 'reader', 'idEncoding'),
    memberships: each(leaves('identity', 'role', 'createdAt')),
    configs: each(leaves('id', 'owner', 'epoch', 'createdAtBlockHeight', 'createdAt', 'enc')),
    wraps: each(leaves('id', 'owner', 'memberId', 'epoch', 'recipientKeyId', 'keyEnabled', 'key')),
    contentQueries: each(leaves('epoch', 'createdAtBlockHeight', 'owner')),
    manifestQueries: each(leaves('headerEpoch', 'createdAtBlockHeight', 'owner')),
  }),
  private_hedge: object({ ...leafFields(...KEY_INPUT, 'rnd', 'plaintextMod251'), doc: leaves(...DOC_KEYS), fields: FIELDS }),
}

function isObj(v: Json | undefined): v is Obj {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

/** Refuse any key the shape does not list, at every depth. */
function checkShape(value: Json, shape: Shape, path: string): void {
  switch (shape.kind) {
    case 'leaf': {
      const scalar = (x: Json) => !isObj(x) && !Array.isArray(x)
      expect(Array.isArray(value) ? value.every(scalar) : scalar(value), `${path}: expected a scalar`).toBe(true)
      return
    }
    case 'each':
      expect(Array.isArray(value), `${path}: expected an array`).toBe(true)
      for (const [i, x] of (value as Json[]).entries()) checkShape(x, shape.of, `${path}[${i}]`)
      return
    case 'values':
      expect(isObj(value), `${path}: expected an object`).toBe(true)
      for (const [k, x] of Object.entries(value as Obj)) checkShape(x, shape.of, `${path}.${k}`)
      return
    case 'object': {
      expect(isObj(value), `${path}: expected an object`).toBe(true)
      const o = value as Obj
      expect(Object.keys(o).filter((k) => !(k in shape.fields)), `${path}: unknown keys`).toEqual([])
      for (const [k, x] of Object.entries(o)) checkShape(x, shape.fields[k] as Shape, `${path}.${k}`)
      return
    }
  }
}

// ---------------------------------------------------------------------------------------------
// Input conversion
// ---------------------------------------------------------------------------------------------

const str = (o: Obj, k: string): string => {
  const v = o[k]
  if (typeof v !== 'string') throw new TypeError(`${k}: expected a string`)
  return v
}
const num = (o: Obj, k: string): number => {
  const v = o[k]
  if (typeof v !== 'number') throw new TypeError(`${k}: expected a number`)
  return v
}
const obj = (o: Obj, k: string): Obj => {
  const v = o[k]
  if (!isObj(v)) throw new TypeError(`${k}: expected an object`)
  return v
}
const arr = (o: Obj, k: string): Obj[] => {
  const v = o[k]
  if (!Array.isArray(v) || !v.every(isObj)) throw new TypeError(`${k}: expected an array of objects`)
  return v as Obj[]
}
const optHex = (o: Obj, k: string): Uint8Array | undefined => (k in o ? hexToBytes(str(o, k)) : undefined)
const hex = (o: Obj, k: string): Uint8Array => hexToBytes(str(o, k))

function mod251(n: number): Uint8Array {
  return Uint8Array.from({ length: n }, (_, i) => i % 251)
}

function plaintextOf(o: Obj): Uint8Array {
  if ('plaintextMod251' in o) return mod251(num(o, 'plaintextMod251'))
  return hex(o, 'plaintextHex')
}

function importKey(o: Obj): Promise<EpochKeys> {
  return EpochKeys.import(hex(o, 'repoId'), num(o, 'epoch'), hex(o, 'key'))
}

function toDoc(d: Obj): PrivateDoc {
  return {
    type: str(d, 'type') as PrivateDocType,
    ownerId: privateId(str(d, 'ownerId')),
    epoch: num(d, 'epoch'),
    number: 'number' in d ? num(d, 'number') : undefined,
    targetId: optHex(d, 'targetId'),
    patchId: optHex(d, 'patchId'),
    refNameHash: optHex(d, 'refNameHash'),
    newOid: optHex(d, 'newOid'),
    prevOid: optHex(d, 'prevOid'),
    force: d['force'] === true,
    baseRefNameHash: optHex(d, 'baseRefNameHash'),
    sourceRefNameHash: optHex(d, 'sourceRefNameHash'),
  }
}

/** The sealed fields of each collaboration type, in TLV order (§4.3). */
const COLLAB_SEALED: Readonly<Record<string, readonly string[]>> = {
  issue: ['title', 'body'],
  patch: ['title', 'body', 'baseRefName', 'sourceRefName'],
  comment: ['body', 'path'],
  review: ['body'],
  event: ['value'],
}

/** The TLV field a sealed property becomes, where the names differ (an event's `value`, tag 15). */
const FIELD_OF: Readonly<Record<string, string>> = { value: 'eventValue' }

/**
 * The reference transform of `private_collab_seal` (the CLI's `collab::private::seal_props`, the
 * web's `lib/repo/private-writes.ts`): the sealed fields leave the plaintext for `enc`, a patch's ref-name
 * hashes become `HMAC(K_ref,e, name)`, and `epoch` + `enc` are added.
 */
async function collabSeal(inp: Obj): Promise<Json> {
  const docType = str(inp, 'docType') as PrivateDocType
  const epoch = num(inp, 'epoch')
  const keys = await importKey(inp)
  const props = obj(inp, 'props')
  const sealed = COLLAB_SEALED[docType] as readonly string[]
  const out: { [k: string]: Json } = {}
  for (const [k, v] of Object.entries(props)) if (!sealed.includes(k)) out[k] = v
  const fields: { [k: string]: string } = {}
  for (const k of sealed) if (k in props) fields[FIELD_OF[k] ?? k] = str(props, k)
  // an importer's provenance: author and url are sealed (TLV 13, 14), createdAt stays
  const imported = props['imported']
  if (isObj(imported)) {
    const kept: { [k: string]: Json } = {}
    for (const [k, v] of Object.entries(imported)) {
      if (k === 'author') fields['importedAuthor'] = String(v)
      else if (k === 'url') fields['importedUrl'] = String(v)
      else kept[k] = v
    }
    out['imported'] = kept
  }
  const doc: PrivateDoc = {
    type: docType,
    ownerId: privateId(str(inp, 'ownerId')),
    epoch,
    number: 'number' in props ? num(props, 'number') : undefined,
    targetId: optHex(props, 'targetId'),
    patchId: optHex(props, 'patchId'),
    baseRefNameHash: fields['baseRefName'] !== undefined ? await refNameHash(keys, fields['baseRefName']) : undefined,
    sourceRefNameHash: fields['sourceRefName'] !== undefined ? await refNameHash(keys, fields['sourceRefName']) : undefined,
  }
  if (docType === 'patch') {
    for (const [k, h] of [['baseRefNameHash', doc.baseRefNameHash], ['sourceRefNameHash', doc.sourceRefNameHash]] as const) {
      delete out[k]
      if (h !== undefined) out[k] = bytesToHex(h)
    }
  }
  try {
    const { enc } = await sealDocWithNonce(keys, doc, fields as DocFields, hex(inp, 'nonce'))
    return { props: { ...out, epoch, enc: bytesToHex(enc) } }
  } catch (e) {
    if (e instanceof TooLargeError) return { error: 'tooLarge' }
    throw e
  }
}

function toFields(f: Obj): DocFields {
  const out: { -readonly [K in keyof DocFields]: DocFields[K] } = {}
  for (const k of ['title', 'body', 'refName', 'baseRefName', 'sourceRefName', 'defaultBranch', 'path', 'importedAuthor', 'importedUrl', 'eventValue'] as const) {
    if (k in f) out[k] = str(f, k)
  }
  const patterns = f['protectedPatterns']
  if (Array.isArray(patterns)) out.protectedPatterns = patterns.map(String)
  if ('prevEpoch' in f) out.prevEpoch = num(f, 'prevEpoch')
  if ('prevEpochKey' in f) out.prevEpochKey = hex(f, 'prevEpochKey')
  if (f['burned'] === true) out.burned = true
  if ('skipEpochKey' in f) out.skipEpochKey = hex(f, 'skipEpochKey')
  return out
}

function fieldsJson(f: DocFields): Json {
  const out: { [k: string]: Json } = {}
  for (const [k, v] of Object.entries(f)) {
    if (v instanceof Uint8Array) out[k] = bytesToHex(v)
    else if (Array.isArray(v)) out[k] = [...v]
    else out[k] = v as Json
  }
  return out
}

function openJson(r: OpenResult): Json {
  if (r.status === 'readable') return { status: 'readable', fields: fieldsJson(r.fields) }
  return r.status === 'unreadable' ? { status: 'unreadable', reason: r.reason } : { status: 'malformed' }
}

async function keyring(repoId: Uint8Array, keys: Obj): Promise<EpochKeyring> {
  const ring = new Map<number, EpochKeys>()
  for (const [e, k] of Object.entries(keys)) {
    ring.set(Number(e), await EpochKeys.import(repoId, Number(e), hexToBytes(String(k))))
  }
  return ring
}

async function packErrorOf(f: () => Promise<Json>): Promise<Json> {
  try {
    return await f()
  } catch (e) {
    if (e instanceof PackError) return { error: e.code }
    throw e
  }
}

// ---------------------------------------------------------------------------------------------
// The evo-sdk wrap harness
// ---------------------------------------------------------------------------------------------

let evo: Evo
let facade: WrapFacade
let repoKeyContract: InstanceType<Evo['DataContract']>

function encryptionKey(pubHex: string): InstanceType<Evo['IdentityPublicKey']> {
  return new evo.IdentityPublicKey({
    keyId: 4,
    purpose: 'encryption',
    securityLevel: 'medium',
    keyType: 'ecdsa_secp256k1',
    data: hexToBytes(pubHex),
  })
}

function repoKeyDocument(repoId: Uint8Array, epoch: number, wrapped: Uint8Array): InstanceType<Evo['Document']> {
  return new evo.Document({
    properties: {
      repoId,
      memberId: new Uint8Array(32).fill(0xb0),
      epoch,
      recipientKeyId: 4,
      senderKeyId: 4,
      wrapped,
    },
    documentTypeName: 'repoKey',
    dataContractId: repoKeyContract.id,
    ownerId: new Uint8Array(32).fill(0xa1),
  })
}

function openVectorWrap(repoId: Uint8Array, epoch: number, wrapped: Uint8Array, readerPriv: string, counterpartyPub: string, anchorCommit: Uint8Array): Promise<EpochKeys> {
  return openWrap(facade, {
    dataContract: repoKeyContract,
    document: repoKeyDocument(repoId, epoch, wrapped),
    readerPrivateKey: evo.PrivateKey.fromHex(readerPriv, 'testnet'),
    counterpartyKey: encryptionKey(counterpartyPub),
    repoId,
    epoch,
    anchorCommit,
  })
}

/** The epoch key behind `keys`, recovered through a wrap round trip (keys are non-extractable). */
async function wrapRoundTrip(inp: Obj, keys: EpochKeys, raw: Uint8Array): Promise<Uint8Array> {
  const props = await sealWrap(facade, keys, raw, {
    dataContract: repoKeyContract,
    senderKey: encryptionKey(str(inp, 'senderPub')),
    senderPrivateKey: evo.PrivateKey.fromHex(str(inp, 'senderPriv'), 'testnet'),
    recipientKey: encryptionKey(str(inp, 'recipientPub')),
  })
  const wrapped = props['wrapped']
  if (!(wrapped instanceof Uint8Array)) throw new TypeError('the SDK returned no wrapped bytes')
  expect(props['recipientKeyId']).toBe(4)
  expect(props['senderKeyId']).toBe(4)
  return wrapped
}

// ---------------------------------------------------------------------------------------------
// Cases
// ---------------------------------------------------------------------------------------------

async function run(v: Vector): Promise<Json> {
  const inp = v.input
  switch (v.case) {
    case 'private_kdf': {
      const repoId = hex(inp, 'repoId')
      const epoch = num(inp, 'epoch')
      const prk = hmac(nobleSha256, repoId, hex(inp, 'key'))
      const sub = (label: string, x?: Uint8Array) => bytesToHex(expand(nobleSha256, prk, subkeyInfo(label, epoch, x), 32))
      const keys = await importKey(inp)
      const out: { [k: string]: Json } = {
        prk: bytesToHex(prk),
        doc: sub('doc'),
        ref: sub('ref'),
        kcv: bytesToHex(keys.kcv),
        commit: bytesToHex(keys.commit),
        hedge: sub('hedge'),
      }
      // The noble KCV/COMMIT agree with the production (WebCrypto) ones
      expect(sub('kcv').slice(0, 28)).toBe(out['kcv'])
      expect(sub('commit')).toBe(out['commit'])
      if ('fileId' in inp) out['pack'] = sub('pack', concat(new Uint8Array([1]), hex(inp, 'fileId')))
      return out
    }
    case 'private_ref_hash': {
      const keys = await importKey(inp)
      const name = str(inp, 'refName')
      return {
        hash: bytesToHex(await refNameHash(keys, name)),
        publicSha256: bytesToHex(await sha256(new TextEncoder().encode(name))),
      }
    }
    case 'private_doc_seal': {
      const doc = toDoc(obj(inp, 'doc'))
      const keys = await EpochKeys.import(hex(inp, 'repoId'), doc.epoch, hex(inp, 'key'))
      try {
        const { ad, tlv, enc } = await sealDocWithNonce(
          keys,
          doc,
          toFields(obj(inp, 'fields')),
          hex(inp, 'nonce'),
          { anchor: inp['anchor'] === true },
        )
        return { ad: bytesToHex(ad), tlv: bytesToHex(tlv), enc: bytesToHex(enc) }
      } catch (e) {
        if (e instanceof MalformedError) return { error: 'malformed' }
        if (e instanceof TooLargeError) return { error: 'tooLarge' }
        throw e
      }
    }
    case 'private_collab_seal':
      return collabSeal(inp)
    case 'private_doc_open': {
      const repoId = hex(inp, 'repoId')
      const c = obj(inp, 'context')
      const d = obj(inp, 'doc')
      const members = c['members']
      const burned = c['burned']
      const ctx: OpenContext = {
        keys: await keyring(repoId, obj(c, 'keys')),
        anchors: new Map(
          Object.entries(obj(c, 'anchors')).map(([e, a]) => [
            Number(e),
            { id: privateId(str(a as Obj, 'id')), height: num(a as Obj, 'height') },
          ]),
        ),
        members: new IdSet(Array.isArray(members) ? members.map((m) => privateId(String(m))) : []),
        burned: new Set(Array.isArray(burned) ? burned.map(Number) : []),
      }
      const doc: StoredPrivateDoc = {
        ...toDoc(d),
        id: 'id' in d ? privateId(str(d, 'id')) : undefined,
        createdAtBlockHeight: 'createdAtBlockHeight' in d ? num(d, 'createdAtBlockHeight') : undefined,
        updatedAtBlockHeight: 'updatedAtBlockHeight' in d ? num(d, 'updatedAtBlockHeight') : undefined,
        enc: hex(d, 'enc'),
      }
      return openJson(await openContent(doc, ctx))
    }
    case 'private_pack_seal': {
      const keys = await importKey(inp)
      const plain = plaintextOf(inp)
      const sealed = await sealPackWithFileId(keys, plain, hex(inp, 'fileId'))
      const header = parseHeader(sealed)
      const nSeg = segmentCount(header.plaintextLen, header.segLog2)
      const S = 2 ** header.segLog2
      const tags = Array.from({ length: nSeg }, (_, i) => {
        const end = Math.min(36 + (i + 1) * (S + 16), sealed.length)
        return bytesToHex(sealed.subarray(end - 16, end))
      })
      const out: { [k: string]: Json } = {
        header: bytesToHex(header.raw),
        segments: nSeg,
        sealedLen: sealed.length,
        tags,
        packHash: bytesToHex(await sha256(sealed)),
        plaintextSha256: bytesToHex(await sha256(plain)),
      }
      if (isObj(v.expected) && 'sealed' in v.expected) out['sealed'] = bytesToHex(sealed)
      // The production open reads back what was sealed
      expect(bytesToHex(await openPack(sealed, sealed.length, new Map([[keys.epoch, keys]])))).toBe(bytesToHex(plain))
      return out
    }
    case 'private_pack_open': {
      const keys = await keyring(hex(inp, 'repoId'), obj(inp, 'keys'))
      return packErrorOf(async () => {
        const plain = await openPack(hex(inp, 'sealed'), num(inp, 'sizeBytes'), keys)
        return { plaintextSha256: bytesToHex(await sha256(plain)), plaintextLen: plain.length }
      })
    }
    case 'private_pack_range': {
      const seal = obj(inp, 'seal')
      const keys = await importKey(seal)
      const sealed = await sealPackWithFileId(keys, plaintextOf(seal), hex(seal, 'fileId'))
      const range = inp['range']
      if (!Array.isArray(range) || range.length !== 2) throw new TypeError('range: expected [a, b]')
      const [a, b] = range.map(Number) as [number, number]
      const fetched: [number, number][] = []
      const fetchRange = async (start: number, end: number) => {
        fetched.push([start, end])
        return sealed.subarray(start, end)
      }
      return packErrorOf(async () => {
        const plan = planRange(parseHeader(sealed), a, b)
        const source = { packHash: bytesToHex(await sha256(sealed)), copy: 'vector', sizeBytes: sealed.length, fetchRange }
        const cache = new PackHeaderCache()
        const output = await readPackRange(source, a, b, new Map([[keys.epoch, keys]]), cache)
        // Exactly the header, then exactly the planned sealed range; the header is cached once authenticated
        expect(fetched).toEqual([[0, 36], [...plan.sealedRange]])
        expect(cache.has(source.packHash, source.copy)).toBe(true)
        return { segments: [...plan.segments], sealedRange: [...plan.sealedRange], output: bytesToHex(output) }
      })
    }
    case 'private_wrap_seal': {
      const repoId = hex(inp, 'repoId')
      const epoch = num(inp, 'epoch')
      const raw = hex(inp, 'key')
      const keys = await EpochKeys.import(repoId, epoch, raw)
      const plaintext = await buildWrapPlaintext(keys, raw)
      const want = v.expected as Obj
      // The raw primitive: AES-256-CBC (PKCS#7) under the vector's shared key and IV
      const iv = hex(inp, 'iv')
      const cbcKey = await crypto.subtle.importKey('raw', hexToBytes(str(want, 'shared')), 'AES-CBC', false, ['encrypt'])
      const ct = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-CBC', iv: new Uint8Array(iv) }, cbcKey, plaintext))
      const wrapped = concat(iv, ct)
      // The SDK derives the same shared key: it opens the vector's bytes in both directions
      const anchorCommit = keys.commit
      for (const [priv, pub] of [
        [str(inp, 'recipientPriv'), str(inp, 'senderPub')],
        [str(inp, 'senderPriv'), str(inp, 'recipientPub')],
      ] as const) {
        const opened = await openVectorWrap(repoId, epoch, wrapped, priv, pub, anchorCommit)
        expect(bytesToHex(opened.commit)).toBe(bytesToHex(keys.commit))
      }
      // And the production seal round-trips through the SDK with its own IV
      const sdkWrapped = await wrapRoundTrip(inp, keys, raw)
      expect(sdkWrapped.length).toBe(64)
      expect(bytesToHex(sdkWrapped.subarray(0, 16))).not.toBe(bytesToHex(iv))
      const back = await openVectorWrap(repoId, epoch, sdkWrapped, str(inp, 'recipientPriv'), str(inp, 'senderPub'), anchorCommit)
      expect(bytesToHex(back.kcv)).toBe(bytesToHex(keys.kcv))
      return { shared: str(want, 'shared'), plaintext: bytesToHex(plaintext), wrapped: bytesToHex(wrapped) }
    }
    case 'private_wrap_open': {
      const repoId = hex(inp, 'repoId')
      const epoch = num(inp, 'epoch')
      try {
        const keys = await openVectorWrap(
          repoId,
          epoch,
          hex(inp, 'wrapped'),
          str(inp, 'readerPriv'),
          str(inp, 'counterpartyPub'),
          hex(inp, 'anchorCommit'),
        )
        // Non-extractable: identify the recovered key by its commitment and KCV instead
        const expected = v.expected as Obj
        const want = await EpochKeys.import(repoId, epoch, hexToBytes(str(expected, 'key')))
        expect(bytesToHex(keys.commit)).toBe(bytesToHex(want.commit))
        expect(bytesToHex(keys.kcv)).toBe(bytesToHex(want.kcv))
        return { key: str(expected, 'key') }
      } catch (e) {
        if (e instanceof WrapError) return { error: e.code }
        throw e
      }
    }
    case 'private_epoch':
      return runEpoch(inp)
    case 'private_hedge': {
      const keys = await importKey(inp)
      const rnd = hex(inp, 'rnd')
      if ('doc' in inp) {
        const doc = toDoc(obj(inp, 'doc'))
        const { ad, tlv } = await sealDocWithNonce(keys, doc, toFields(obj(inp, 'fields')), new Uint8Array(12))
        expect(bytesToHex(tlv)).toBe(bytesToHex(buildTlv(toFields(obj(inp, 'fields')), { type: doc.type, epoch: doc.epoch })))
        return { nonce: bytesToHex(await hedgedNonce(keys, rnd, ad, tlv)) }
      }
      return { fileId: bytesToHex(await hedgedFileId(keys, rnd, plaintextOf(inp))) }
    }
    default:
      throw new Error(`unknown private vector case: ${v.case}`)
  }
}

async function runEpoch(inp: Obj): Promise<Json> {
  const repoId = hex(inp, 'repoId')
  const encoding: IdEncoding = 'idEncoding' in inp ? (str(inp, 'idEncoding') as IdEncoding) : 'hex'
  expect(['hex', 'base58']).toContain(encoding)
  const id = (o: Obj, k: string) => privateId(str(o, k))
  const out = (b: Uint8Array) => encodePrivateId(b, encoding)
  const memberships: PrivateMembership[] = arr(inp, 'memberships').map((m) => ({
    identity: id(m, 'identity'),
    role: str(m, 'role') as PrivateMembership['role'],
  }))
  const configs: ConfigRow[] = arr(inp, 'configs').map((c) => ({
    id: id(c, 'id'),
    owner: id(c, 'owner'),
    epoch: num(c, 'epoch'),
    createdAtBlockHeight: num(c, 'createdAtBlockHeight'),
    enc: hex(c, 'enc'),
  }))
  const wraps: WrapRow[] = []
  for (const w of arr(inp, 'wraps')) {
    const epoch = num(w, 'epoch')
    wraps.push({
      id: id(w, 'id'),
      owner: id(w, 'owner'),
      memberId: id(w, 'memberId'),
      epoch,
      recipientKeyId: num(w, 'recipientKeyId'),
      keyEnabled: w['keyEnabled'] === true,
      keys: 'key' in w ? await EpochKeys.import(repoId, epoch, hex(w, 'key')) : undefined,
    })
  }
  const r = await resolveEpochs({ repoId, reader: id(inp, 'reader'), memberships, configs, wraps })
  const result: { [k: string]: Json } = {
    currentEpoch: r.currentEpoch,
    anchors: Object.fromEntries([...r.anchors].map(([e, a]) => [String(e), out(a.id)])),
    readable: [...r.keys.keys()].sort((a, b) => a - b),
    writeEpoch: r.writeEpoch,
    unanchored: [...r.unanchored],
    alerts: r.alerts.map(
      (a): Json =>
        'author' in a
          ? { kind: a.kind, epoch: a.epoch, author: out(a.author) }
          : { kind: a.kind, epoch: a.epoch, members: a.members.map(out) },
    ),
    repair:
      r.repair === null
        ? null
        : { rotate: r.repair.rotate, nonMembers: r.repair.nonMembers.map(out), missingWraps: r.repair.missingWraps.map(out) },
  }
  if ('contentQueries' in inp) {
    result['content'] = arr(inp, 'contentQueries').map((q) =>
      contentIsLate(r, num(q, 'epoch'), num(q, 'createdAtBlockHeight'), id(q, 'owner')) ? 'late' : 'shown',
    )
  }
  if ('manifestQueries' in inp) {
    result['manifests'] = arr(inp, 'manifestQueries').map((q) => ({
      ...manifestStanding(r, num(q, 'headerEpoch'), num(q, 'createdAtBlockHeight'), id(q, 'owner')),
    }))
  }
  return result
}

// ---------------------------------------------------------------------------------------------

describe('private-repository conformance vectors', () => {
  const vectors: Vector[] = PRIVATE_FILES.map((f) => JSON.parse(readFileSync(resolve(VECTORS_DIR, f), 'utf8')) as Vector)
  let ran = 0

  beforeAll(async () => {
    evo = await import('@dashevo/evo-sdk')
    await evo.EvoSDK.getLatestVersionNumber()
    // `repoKey` is a forge-collab type (RC1 layout O-03); its gates name forge-core, whose id the
    // deploy script substitutes (any valid id parses)
    const text = readFileSync(resolve(ROOT, 'forge-contracts', 'contracts', 'forge-collab.json'), 'utf8').replaceAll(
      'FORGE_CORE_CONTRACT_ID',
      'A2KL77ngVM1ft1t1em2XKt1rWCBZANdAJMyfWrDGCcd1',
    )
    repoKeyContract = evo.DataContract.fromJSON(JSON.parse(text) as Parameters<Evo['DataContract']['fromJSON']>[0], true, 14)
    facade = new evo.EvoSDK().encryptedFor
  })

  for (const v of vectors) {
    it(`${v.case} :: ${v.name}`, async () => {
      expect(v.case.startsWith('private_')).toBe(true)
      expect(v.rules).toBe('v2')
      const shape = SHAPES[v.case]
      if (shape === undefined) throw new Error(`unknown private vector case: ${v.case}`)
      checkShape(v.input, shape, `${v.name}.input`)
      expect(await run(v)).toEqual(v.expected)
      ran++
    })
  }

  it('ran every private vector file', () => {
    expect(PRIVATE_FILES.length).toBeGreaterThanOrEqual(221)
    expect(ran).toBe(PRIVATE_FILES.length)
  })
})
