/**
 * THE PARITY PROOF — for the private-repository crypto core.
 *
 * Runs every `forge-contracts/vectors/private_*.json` (`docs/security/private-repos.md` §11,
 * generated by `tools/private-repos-vectors/gen.py`) against `lib/private`; the Rust
 * `forge-core::private` runs the same files. Each case has an allow-list of input keys at
 * every depth, so a vector cannot carry a field this harness would silently ignore.
 *
 * `private_kdf` expects raw subkey bytes that non-extractable WebCrypto keys cannot reveal, so
 * those are checked with @noble/hashes; KCV and COMMIT go through the production path, and
 * every other subkey is covered byte for byte by the doc, ref, pack and hedge vectors.
 */

import { readFileSync, readdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { expand } from '@noble/hashes/hkdf.js'
import { hmac } from '@noble/hashes/hmac.js'
import { sha256 as nobleSha256 } from '@noble/hashes/sha2.js'
import { beforeAll, describe, expect, it } from 'vitest'

import { bytesToHex, concat, hexToBytes, sha256 } from './bytes'
import {
  TooLargeError,
  V4,
  docAdWithoutKeys,
  maxLetterPlaintext,
  openContent,
  padded,
  type OpenContext,
  type OpenResult,
  type PrivateDoc,
  type StoredPrivateDoc,
} from './doc'
import {
  contentIsLate,
  manifestStanding,
  resolveEpochs,
  type ConfigRow,
  type PrivateMembership,
  type WrapRow,
} from './epoch'
import { EpochKeys, refNameHash, releaseTagHash, releaseTagName, subkeyInfo, type EpochKeyring } from './keys'
import { PackError, PackHeaderCache, openPack, parseHeader, planRange, readPackRange, segmentCount } from './pack'
import {
  ManifestMismatchError,
  foldReleases,
  openRelease,
  openReleaseManifest,
  sealRelease,
  sealReleaseManifest,
  type ReleaseFields,
  type ReleaseManifest,
  type ReleaseOpenResult,
  type ReleaseStatus,
  type StoredRelease,
} from './release'
import { ArtifactError, openLetter, openLetterArtifact, letterSharedKey, type LetterOpenResult, type OwnerKey } from './named'
import { buildTlv, encodeRecipients, MalformedError, type DocFields, type PrivateDocType } from './tlv'
import { WrapError, buildWrapPlaintext, openWrap, sealWrap, type WrapFacade } from './wrap'
import {
  hedgedFileId,
  hedgedNonce,
  sealDocWithNonce,
  sealLetterArtifactWith,
  sealLetterWith,
  sealMembersDocWithNonce,
  sealPackWithFileId,
  sealReleaseManifestWithFileId,
  sealReleaseWithNonce,
} from './testing'
import { IdSet, encodePrivateId, privateId, type IdEncoding } from './ids'

type Evo = typeof import('@dashevo/evo-sdk')
type Json = null | boolean | number | string | Json[] | { [k: string]: Json }
type Obj = { readonly [k: string]: Json }

interface Vector {
  readonly name: string
  readonly description: string
  readonly case: string
  readonly rules: string
  readonly input: Obj
  readonly expected: Json
}

const ROOT = resolve(process.cwd(), '..')
const VECTORS_DIR = resolve(ROOT, 'forge-contracts', 'vectors')
/** The private-repository cases and the mixed-visibility envelopes (members-only, specific people). */
const CRYPTO_PREFIXES = ['private_', 'mixed_doc_', 'named_envelope', 'named_artifact']
const isCryptoCase = (name: string) => CRYPTO_PREFIXES.some((p) => name.startsWith(p))
const PRIVATE_FILES = readdirSync(VECTORS_DIR)
  .filter((f) => isCryptoCase(f) && f.endsWith('.json'))
  .sort()

// ---------------------------------------------------------------------------------------------
// Input allow-lists
// ---------------------------------------------------------------------------------------------

/** An input shape: a scalar (or scalar array), an array of shapes, a map of shapes, or exact keys. */
type Shape =
  | { readonly kind: 'leaf' }
  | { readonly kind: 'each'; readonly of: Shape }
  | { readonly kind: 'values'; readonly of: Shape }
  | { readonly kind: 'object'; readonly fields: { readonly [k: string]: Shape } }

const LEAF: Shape = { kind: 'leaf' }
const each = (of: Shape): Shape => ({ kind: 'each', of })
const values = (of: Shape): Shape => ({ kind: 'values', of })
const object = (fields: { readonly [k: string]: Shape }): Shape => ({ kind: 'object', fields })
const leafFields = (...keys: string[]) => Object.fromEntries(keys.map((k) => [k, LEAF]))
const leaves = (...keys: string[]): Shape => object(leafFields(...keys))

const DOC_KEYS = [
  'type', 'ownerId', 'epoch', 'number', 'targetId', 'patchId', 'refNameHash', 'newOid', 'prevOid',
  'force', 'baseRefNameHash', 'sourceRefNameHash',
]
const FIELDS = leaves(
  'title', 'body', 'refName', 'baseRefName', 'sourceRefName', 'defaultBranch', 'protectedPatterns',
  'prevEpoch', 'prevEpochKey', 'path', 'burned', 'skipEpochKey', 'importedAuthor', 'importedUrl', 'eventValue',
)
const KEY_INPUT = ['repoId', 'key', 'epoch']
const SEAL_PACK = leaves(...KEY_INPUT, 'fileId', 'plaintextMod251', 'plaintextHex')
const OPEN_CONTEXT = object({ keys: values(LEAF), anchors: values(leaves('id', 'height', 'statedHeight')), members: LEAF, burned: LEAF })
const RELEASE_FIELDS = leaves(
  'tag', 'name', 'notes', 'targetOid', 'prerelease', 'draft', 'yanked', 'unpublished', 'notesContinue',
  'importedAuthor', 'importedUrl', 'importedCreatedAt', 'assetManifest',
)
const RELEASE_MANIFEST = object({
  ...leafFields('v', 'tag', 'total', 'source', 'notes'),
  assets: each(object({ ...leafFields('name', 'sha256', 'sizeBytes', 'sealedSha256', 'sealedSizeBytes'), uris: LEAF })),
})

const MIXED_DOC = leaves(...DOC_KEYS, 'vis')
const PARTY = leaves('identityId', 'priv', 'pub', 'keyId')

const SHAPES: Readonly<Record<string, Shape>> = {
  mixed_doc_seal: object({ ...leafFields('repoId', 'key', 'nonce'), doc: MIXED_DOC, fields: FIELDS }),
  mixed_doc_open: object({
    repoId: LEAF,
    context: OPEN_CONTEXT,
    doc: leaves(...DOC_KEYS, 'vis', 'id', 'createdAtBlockHeight', 'updatedAtBlockHeight', 'enc'),
  }),
  named_envelope: object({
    ...leafFields('repoId', 'kObj', 'nonce', 'ivs'),
    doc: MIXED_DOC,
    fields: FIELDS,
    sender: PARTY,
    recipients: each(PARTY),
  }),
  named_artifact: object({
    ...leafFields('repoId', 'ownerId', 'kObj', 'fileId', 'ivs', 'plaintextHex'),
    sender: PARTY,
    recipients: each(PARTY),
  }),
  named_artifact_open: object({
    ...leafFields('repoId', 'sealed', 'sizeBytes'),
    ownerKeys: each(leaves('id', 'purpose', 'keyType', 'data')),
    readers: each(leaves('identityId', 'keys')),
  }),
  named_envelope_open: object({
    repoId: LEAF,
    doc: leaves(...DOC_KEYS, 'vis', 'enc'),
    ownerKeys: each(leaves('id', 'purpose', 'keyType', 'data')),
    readers: each(leaves('identityId', 'keys')),
  }),
  private_kdf: leaves(...KEY_INPUT, 'fileId'),
  private_ref_hash: leaves(...KEY_INPUT, 'refName'),
  private_doc_seal: object({ ...leafFields('repoId', 'key', 'nonce', 'anchor'), doc: leaves(...DOC_KEYS), fields: FIELDS }),
  private_doc_open: object({
    repoId: LEAF,
    context: OPEN_CONTEXT,
    doc: leaves(...DOC_KEYS, 'id', 'createdAtBlockHeight', 'updatedAtBlockHeight', 'enc'),
  }),
  private_collab_seal: object({
    ...leafFields('repoId', 'key', 'epoch', 'ownerId', 'docType', 'nonce'),
    props: object({
      ...leafFields('number', 'title', 'body', 'baseRefName', 'baseRefNameHash', 'sourceRefName', 'sourceRefNameHash', 'sourceRepoId', 'headOid', 'patchManifestHash', 'draft', 'targetId', 'path', 'replyTo', 'reviewId', 'commitOid', 'line', 'startLine', 'side', 'patchId', 'verdict', 'commentCount', 'targetNumber', 'kind', 'value', 'refId'),
      imported: leaves('author', 'createdAt', 'url'),
    }),
  }),
  private_pack_seal: SEAL_PACK,
  private_pack_open: object({ ...leafFields('repoId', 'sealed', 'sizeBytes'), keys: values(LEAF) }),
  private_pack_range: object({ seal: SEAL_PACK, range: LEAF }),
  private_wrap_seal: leaves('repoId', 'senderPriv', 'senderPub', 'recipientPriv', 'recipientPub', 'key', 'epoch', 'iv'),
  private_wrap_open: leaves('repoId', 'epoch', 'wrapped', 'readerPriv', 'counterpartyPub', 'anchorCommit'),
  private_epoch: object({
    ...leafFields('repoId', 'reader', 'idEncoding'),
    memberships: each(leaves('identity', 'role', 'createdAt')),
    configs: each(leaves('id', 'owner', 'epoch', 'createdAtBlockHeight', 'createdAt', 'enc')),
    wraps: each(leaves('id', 'owner', 'memberId', 'epoch', 'recipientKeyId', 'keyEnabled', 'key')),
    contentQueries: each(leaves('epoch', 'createdAtBlockHeight', 'owner')),
    manifestQueries: each(leaves('headerEpoch', 'createdAtBlockHeight', 'owner')),
  }),
  private_hedge: object({ ...leafFields(...KEY_INPUT, 'rnd', 'plaintextMod251'), doc: leaves(...DOC_KEYS), fields: FIELDS }),
  private_release_seal: object({
    ...leafFields(...KEY_INPUT, 'ownerId', 'nonce', 'fileId'),
    fields: RELEASE_FIELDS,
    manifest: RELEASE_MANIFEST,
  }),
  private_release_open: object({
    repoId: LEAF,
    context: OPEN_CONTEXT,
    doc: object({ ...leafFields('ownerId', 'epoch', 'tagName', 'vis', 'delta', 'enc', 'yanked'), imported: leaves('url') }),
    keys: values(LEAF),
    manifest: leaves('sealed', 'sizeBytes', 'assetManifest', 'tag', 'notesContinue'),
  }),
  private_release_fold: object({
    revisions: each(object({
      ...leafFields('id', 'createdAt', 'epoch', 'tagName', 'status', 'enc'),
      fields: leaves('tag', 'draft', 'unpublished', 'yanked'),
    })),
  }),
}

function isObj(v: Json | undefined): v is Obj {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

/** Refuse any key the shape does not list, at every depth. */
function checkShape(value: Json, shape: Shape, path: string): void {
  switch (shape.kind) {
    case 'leaf': {
      const scalar = (x: Json) => !isObj(x) && !Array.isArray(x)
      expect(Array.isArray(value) ? value.every(scalar) : scalar(value), `${path}: expected a scalar`).toBe(true)
      return
    }
    case 'each':
      expect(Array.isArray(value), `${path}: expected an array`).toBe(true)
      for (const [i, x] of (value as Json[]).entries()) checkShape(x, shape.of, `${path}[${i}]`)
      return
    case 'values':
      expect(isObj(value), `${path}: expected an object`).toBe(true)
      for (const [k, x] of Object.entries(value as Obj)) checkShape(x, shape.of, `${path}.${k}`)
      return
    case 'object': {
      expect(isObj(value), `${path}: expected an object`).toBe(true)
      const o = value as Obj
      expect(Object.keys(o).filter((k) => !(k in shape.fields)), `${path}: unknown keys`).toEqual([])
      for (const [k, x] of Object.entries(o)) checkShape(x, shape.fields[k] as Shape, `${path}.${k}`)
      return
    }
  }
}

// ---------------------------------------------------------------------------------------------
// Input conversion
// ---------------------------------------------------------------------------------------------

const str = (o: Obj, k: string): string => {
  const v = o[k]
  if (typeof v !== 'string') throw new TypeError(`${k}: expected a string`)
  return v
}
const num = (o: Obj, k: string): number => {
  const v = o[k]
  if (typeof v !== 'number') throw new TypeError(`${k}: expected a number`)
  return v
}
const obj = (o: Obj, k: string): Obj => {
  const v = o[k]
  if (!isObj(v)) throw new TypeError(`${k}: expected an object`)
  return v
}
const arr = (o: Obj, k: string): Obj[] => {
  const v = o[k]
  if (!Array.isArray(v) || !v.every(isObj)) throw new TypeError(`${k}: expected an array of objects`)
  return v as Obj[]
}
const optHex = (o: Obj, k: string): Uint8Array | undefined => (k in o ? hexToBytes(str(o, k)) : undefined)
const hex = (o: Obj, k: string): Uint8Array => hexToBytes(str(o, k))

function mod251(n: number): Uint8Array {
  return Uint8Array.from({ length: n }, (_, i) => i % 251)
}

function plaintextOf(o: Obj): Uint8Array {
  if ('plaintextMod251' in o) return mod251(num(o, 'plaintextMod251'))
  return hex(o, 'plaintextHex')
}

function importKey(o: Obj): Promise<EpochKeys> {
  return EpochKeys.import(hex(o, 'repoId'), num(o, 'epoch'), hex(o, 'key'))
}

function toDoc(d: Obj): PrivateDoc {
  return {
    type: str(d, 'type') as PrivateDocType,
    vis: 'vis' in d ? (str(d, 'vis') as 'public' | 'private') : undefined,
    ownerId: privateId(str(d, 'ownerId')),
    epoch: num(d, 'epoch'),
    number: 'number' in d ? num(d, 'number') : undefined,
    targetId: optHex(d, 'targetId'),
    patchId: optHex(d, 'patchId'),
    refNameHash: optHex(d, 'refNameHash'),
    newOid: optHex(d, 'newOid'),
    prevOid: optHex(d, 'prevOid'),
    force: d['force'] === true,
    baseRefNameHash: optHex(d, 'baseRefNameHash'),
    sourceRefNameHash: optHex(d, 'sourceRefNameHash'),
  }
}

/** The sealed fields of each collaboration type, in TLV order (§4.3). */
const COLLAB_SEALED: Readonly<Record<string, readonly string[]>> = {
  issue: ['title', 'body'],
  patch: ['title', 'body', 'baseRefName', 'sourceRefName'],
  comment: ['body', 'path'],
  review: ['body'],
  event: ['value'],
}

/** The TLV field a sealed property becomes, where the names differ (an event's `value`, tag 15). */
const FIELD_OF: Readonly<Record<string, string>> = { value: 'eventValue' }

/**
 * The reference transform of `private_collab_seal` (the CLI's `collab::private::seal_props`, the
 * web's `lib/repo/private-writes.ts`): the sealed fields leave the plaintext for `enc`, a patch's ref-name
 * hashes become `HMAC(K_ref,e, name)`, and `epoch` + `enc` are added.
 */
async function collabSeal(inp: Obj): Promise<Json> {
  const docType = str(inp, 'docType') as PrivateDocType
  const epoch = num(inp, 'epoch')
  const keys = await importKey(inp)
  const props = obj(inp, 'props')
  const sealed = COLLAB_SEALED[docType] as readonly string[]
  const out: { [k: string]: Json } = {}
  for (const [k, v] of Object.entries(props)) if (!sealed.includes(k)) out[k] = v
  const fields: { [k: string]: string } = {}
  for (const k of sealed) if (k in props) fields[FIELD_OF[k] ?? k] = str(props, k)
  // an importer's provenance: author and url are sealed (TLV 13, 14), createdAt stays
  const imported = props['imported']
  if (isObj(imported)) {
    const kept: { [k: string]: Json } = {}
    for (const [k, v] of Object.entries(imported)) {
      if (k === 'author') fields['importedAuthor'] = String(v)
      else if (k === 'url') fields['importedUrl'] = String(v)
      else kept[k] = v
    }
    out['imported'] = kept
  }
  const doc: PrivateDoc = {
    type: docType,
    ownerId: privateId(str(inp, 'ownerId')),
    epoch,
    number: 'number' in props ? num(props, 'number') : undefined,
    targetId: optHex(props, 'targetId'),
    patchId: optHex(props, 'patchId'),
    baseRefNameHash: fields['baseRefName'] !== undefined ? await refNameHash(keys, fields['baseRefName']) : undefined,
    sourceRefNameHash: fields['sourceRefName'] !== undefined ? await refNameHash(keys, fields['sourceRefName']) : undefined,
  }
  if (docType === 'patch') {
    for (const [k, h] of [['baseRefNameHash', doc.baseRefNameHash], ['sourceRefNameHash', doc.sourceRefNameHash]] as const) {
      delete out[k]
      if (h !== undefined) out[k] = bytesToHex(h)
    }
  }
  try {
    const { enc } = await sealDocWithNonce(keys, doc, fields as DocFields, hex(inp, 'nonce'))
    return { props: { ...out, epoch, enc: bytesToHex(enc) } }
  } catch (e) {
    if (e instanceof TooLargeError) return { error: 'tooLarge' }
    throw e
  }
}

function toFields(f: Obj): DocFields {
  const out: { -readonly [K in keyof DocFields]: DocFields[K] } = {}
  for (const k of ['title', 'body', 'refName', 'baseRefName', 'sourceRefName', 'defaultBranch', 'path', 'importedAuthor', 'importedUrl', 'eventValue'] as const) {
    if (k in f) out[k] = str(f, k)
  }
  const patterns = f['protectedPatterns']
  if (Array.isArray(patterns)) out.protectedPatterns = patterns.map(String)
  if ('prevEpoch' in f) out.prevEpoch = num(f, 'prevEpoch')
  if ('prevEpochKey' in f) out.prevEpochKey = hex(f, 'prevEpochKey')
  if (f['burned'] === true) out.burned = true
  if ('skipEpochKey' in f) out.skipEpochKey = hex(f, 'skipEpochKey')
  return out
}

function fieldsJson(f: DocFields): Json {
  const out: { [k: string]: Json } = {}
  for (const [k, v] of Object.entries(f)) {
    if (v instanceof Uint8Array) out[k] = bytesToHex(v)
    else if (Array.isArray(v)) out[k] = [...v]
    else out[k] = v as Json
  }
  return out
}

function openJson(r: OpenResult): Json {
  if (r.status === 'readable') return { status: 'readable', fields: fieldsJson(r.fields) }
  return r.status === 'unreadable' ? { status: 'unreadable', reason: r.reason } : { status: 'malformed' }
}

function letterJson(r: LetterOpenResult): Json {
  if (r.status === 'readable') {
    return { status: 'readable', fields: fieldsJson(r.fields), recipients: r.recipients.map(bytesToHex), slot: r.slot }
  }
  return r.status === 'unreadable' ? { status: 'unreadable', reason: r.reason } : { status: 'malformed' }
}

function storedDoc(d: Obj): StoredPrivateDoc {
  return {
    ...toDoc(d),
    id: 'id' in d ? privateId(str(d, 'id')) : undefined,
    createdAtBlockHeight: 'createdAtBlockHeight' in d ? num(d, 'createdAtBlockHeight') : undefined,
    updatedAtBlockHeight: 'updatedAtBlockHeight' in d ? num(d, 'updatedAtBlockHeight') : undefined,
    enc: hex(d, 'enc'),
  }
}

/** `named_envelope`: the deterministic seal, every intermediate, every recipient's open and the SDK drift check. */
async function namedEnvelope(inp: Obj): Promise<Json> {
  const repoId = hex(inp, 'repoId')
  const doc = toDoc(obj(inp, 'doc'))
  const fields = toFields(obj(inp, 'fields'))
  const sender = obj(inp, 'sender')
  const recipients = arr(inp, 'recipients')
  const ivs = inp['ivs']
  if (!Array.isArray(ivs)) throw new TypeError('ivs: expected an array')
  const kObj = hex(inp, 'kObj')
  const sealed = await sealLetterWith(
    repoId,
    hex(sender, 'priv'),
    num(sender, 'keyId'),
    doc,
    fields,
    recipients.map((r) => ({ identityId: hex(r, 'identityId'), publicKey: hex(r, 'pub') })),
    kObj,
    hex(inp, 'nonce'),
    ivs.map((x) => hexToBytes(String(x))),
  )
  // The intermediates, recomputed from their definitions rather than read back from the seal
  const n = recipients.length
  const body = concat(buildTlv(fields, { type: doc.type, epoch: 0 }), encodeRecipients(recipients.map((r) => hex(r, 'identityId'))))
  expect(bytesToHex(sealed.tlv)).toBe(bytesToHex(padded(doc.type, body, maxLetterPlaintext(doc.type, n))))
  expect(bytesToHex(sealed.head)).toBe(bytesToHex(sealed.enc.subarray(1, 38 + 64 * n)))
  expect(bytesToHex(sealed.ad)).toBe(bytesToHex(concat(docAdWithoutKeys(doc, repoId, V4), await sha256(sealed.head))))
  // The SDK's own decrypt opens every slot to 0x02 ‖ KCV_obj ‖ K_obj (drift check)
  for (const [i, r] of recipients.entries()) {
    const slot = sealed.head.subarray(37 + 64 * i, 37 + 64 * (i + 1))
    const pt = await facade.decrypt({
      dataContract: repoKeyContract,
      document: repoKeyDocument(repoId, 0, slot),
      property: 'wrapped',
      recipientPrivateKey: evo.PrivateKey.fromHex(str(r, 'priv'), 'testnet'),
      senderKey: encryptionKey(str(sender, 'pub')),
    })
    expect(bytesToHex(pt)).toBe(bytesToHex(concat(new Uint8Array([0x02]), sealed.commit.subarray(0, 14), kObj)))
  }
  const ownerKeys: OwnerKey[] = [{ id: num(sender, 'keyId'), purpose: 1, keyType: 0, data: hex(sender, 'pub') }]
  const stored: StoredPrivateDoc = { ...doc, enc: sealed.enc }
  const opened: Json[] = []
  for (const r of recipients) {
    opened.push(letterJson(await openLetter(repoId, stored, ownerKeys, { identityId: hex(r, 'identityId'), secrets: [hex(r, 'priv')] })))
  }
  return {
    shared: await Promise.all(recipients.map(async (r) => bytesToHex(await letterSharedKey(hex(sender, 'priv'), hex(r, 'pub'))))),
    commit: bytesToHex(sealed.commit),
    kcv: bytesToHex(sealed.commit.subarray(0, 14)),
    headerSha256: bytesToHex(await sha256(sealed.head)),
    ad: bytesToHex(sealed.ad),
    tlv: bytesToHex(sealed.tlv),
    enc: bytesToHex(sealed.enc),
    opened,
  }
}

async function keyring(repoId: Uint8Array, keys: Obj): Promise<EpochKeyring> {
  const ring = new Map<number, EpochKeys>()
  for (const [e, k] of Object.entries(keys)) {
    ring.set(Number(e), await EpochKeys.import(repoId, Number(e), hexToBytes(String(k))))
  }
  return ring
}

/** A reader's context in §11's vector shape. */
async function openContextOf(repoId: Uint8Array, c: Obj): Promise<OpenContext> {
  const members = c['members']
  const burned = c['burned']
  return {
    keys: await keyring(repoId, obj(c, 'keys')),
    anchors: new Map(
      Object.entries(obj(c, 'anchors')).map(([e, v]) => {
        const a = v as Obj
        // stated(e) defaults to the anchor's own height: the anchor first stated its key
        const statedHeight = num(a, a['statedHeight'] === undefined ? 'height' : 'statedHeight')
        return [Number(e), { id: privateId(str(a, 'id')), height: num(a, 'height'), statedHeight }]
      }),
    ),
    members: new IdSet(Array.isArray(members) ? members.map((m) => privateId(String(m))) : []),
    burned: new Set(Array.isArray(burned) ? burned.map(Number) : []),
  }
}

async function packErrorOf(f: () => Promise<Json>): Promise<Json> {
  try {
    return await f()
  } catch (e) {
    if (e instanceof PackError) return { error: e.code }
    throw e
  }
}

// ---------------------------------------------------------------------------------------------
// The evo-sdk wrap harness
// ---------------------------------------------------------------------------------------------

let evo: Evo
let facade: WrapFacade
let repoKeyContract: InstanceType<Evo['DataContract']>

function encryptionKey(pubHex: string): InstanceType<Evo['IdentityPublicKey']> {
  return new evo.IdentityPublicKey({
    keyId: 4,
    purpose: 'encryption',
    securityLevel: 'medium',
    keyType: 'ecdsa_secp256k1',
    data: hexToBytes(pubHex),
  })
}

function repoKeyDocument(repoId: Uint8Array, epoch: number, wrapped: Uint8Array): InstanceType<Evo['Document']> {
  return new evo.Document({
    properties: {
      repoId,
      memberId: new Uint8Array(32).fill(0xb0),
      epoch,
      recipientKeyId: 4,
      senderKeyId: 4,
      wrapped,
    },
    documentTypeName: 'repoKey',
    dataContractId: repoKeyContract.id,
    ownerId: new Uint8Array(32).fill(0xa1),
  })
}

function openVectorWrap(repoId: Uint8Array, epoch: number, wrapped: Uint8Array, readerPriv: string, counterpartyPub: string, anchorCommit: Uint8Array): Promise<EpochKeys> {
  return openWrap(facade, {
    dataContract: repoKeyContract,
    document: repoKeyDocument(repoId, epoch, wrapped),
    readerPrivateKey: evo.PrivateKey.fromHex(readerPriv, 'testnet'),
    counterpartyKey: encryptionKey(counterpartyPub),
    repoId,
    epoch,
    anchorCommit,
  })
}

/** The epoch key behind `keys`, recovered through a wrap round trip (keys are non-extractable). */
async function wrapRoundTrip(inp: Obj, keys: EpochKeys, raw: Uint8Array): Promise<Uint8Array> {
  const props = await sealWrap(facade, keys, raw, {
    dataContract: repoKeyContract,
    senderKey: encryptionKey(str(inp, 'senderPub')),
    senderPrivateKey: evo.PrivateKey.fromHex(str(inp, 'senderPriv'), 'testnet'),
    recipientKey: encryptionKey(str(inp, 'recipientPub')),
  })
  const wrapped = props['wrapped']
  if (!(wrapped instanceof Uint8Array)) throw new TypeError('the SDK returned no wrapped bytes')
  expect(props['recipientKeyId']).toBe(4)
  expect(props['senderKeyId']).toBe(4)
  return wrapped
}

// ---------------------------------------------------------------------------------------------
// Cases
// ---------------------------------------------------------------------------------------------

async function run(v: Vector): Promise<Json> {
  const inp = v.input
  switch (v.case) {
    case 'private_kdf': {
      const repoId = hex(inp, 'repoId')
      const epoch = num(inp, 'epoch')
      const prk = hmac(nobleSha256, repoId, hex(inp, 'key'))
      const sub = (label: string, x?: Uint8Array) => bytesToHex(expand(nobleSha256, prk, subkeyInfo(label, epoch, x), 32))
      const keys = await importKey(inp)
      const out: { [k: string]: Json } = {
        prk: bytesToHex(prk),
        doc: sub('doc'),
        ref: sub('ref'),
        kcv: bytesToHex(keys.kcv),
        commit: bytesToHex(keys.commit),
        hedge: sub('hedge'),
      }
      // The noble KCV/COMMIT agree with the production (WebCrypto) ones
      expect(sub('kcv').slice(0, 28)).toBe(out['kcv'])
      expect(sub('commit')).toBe(out['commit'])
      if ('fileId' in inp) out['pack'] = sub('pack', concat(new Uint8Array([1]), hex(inp, 'fileId')))
      return out
    }
    case 'private_ref_hash': {
      const keys = await importKey(inp)
      const name = str(inp, 'refName')
      return {
        hash: bytesToHex(await refNameHash(keys, name)),
        publicSha256: bytesToHex(await sha256(new TextEncoder().encode(name))),
      }
    }
    case 'private_doc_seal': {
      const doc = toDoc(obj(inp, 'doc'))
      const keys = await EpochKeys.import(hex(inp, 'repoId'), doc.epoch, hex(inp, 'key'))
      try {
        const { ad, tlv, enc } = await sealDocWithNonce(
          keys,
          doc,
          toFields(obj(inp, 'fields')),
          hex(inp, 'nonce'),
          { anchor: inp['anchor'] === true },
        )
        return { ad: bytesToHex(ad), tlv: bytesToHex(tlv), enc: bytesToHex(enc) }
      } catch (e) {
        if (e instanceof MalformedError) return { error: 'malformed' }
        if (e instanceof TooLargeError) return { error: 'tooLarge' }
        throw e
      }
    }
    case 'private_collab_seal':
      return collabSeal(inp)
    case 'mixed_doc_seal': {
      const doc = toDoc(obj(inp, 'doc'))
      const keys = await EpochKeys.import(hex(inp, 'repoId'), doc.epoch, hex(inp, 'key'))
      try {
        const r = await sealMembersDocWithNonce(keys, doc, toFields(obj(inp, 'fields')), hex(inp, 'nonce'))
        return { ad: bytesToHex(r.ad), kObj: bytesToHex(r.kObj), commit: bytesToHex(r.commit), tlv: bytesToHex(r.tlv), enc: bytesToHex(r.enc) }
      } catch (e) {
        if (e instanceof MalformedError) return { error: 'malformed' }
        if (e instanceof TooLargeError) return { error: 'tooLarge' }
        throw e
      }
    }
    case 'mixed_doc_open': {
      const repoId = hex(inp, 'repoId')
      return openJson(await openContent(storedDoc(obj(inp, 'doc')), await openContextOf(repoId, obj(inp, 'context'))))
    }
    case 'named_envelope':
      return namedEnvelope(inp)
    case 'named_artifact': {
      const repoId = hex(inp, 'repoId')
      const sender = obj(inp, 'sender')
      const recipients = arr(inp, 'recipients')
      const ivs = inp['ivs']
      if (!Array.isArray(ivs)) throw new TypeError('ivs: expected an array')
      const kObj = hex(inp, 'kObj')
      const fileId = hex(inp, 'fileId')
      const plain = hex(inp, 'plaintextHex')
      const sealed = await sealLetterArtifactWith(
        repoId,
        hex(sender, 'priv'),
        num(sender, 'keyId'),
        hex(inp, 'ownerId'),
        recipients.map((r) => ({ identityId: hex(r, 'identityId'), publicKey: hex(r, 'pub') })),
        plain,
        kObj,
        fileId,
        ivs.map((x) => hexToBytes(String(x))),
      )
      const ownerKeys: OwnerKey[] = [{ id: num(sender, 'keyId'), purpose: 1, keyType: 0, data: hex(sender, 'pub') }]
      for (const r of recipients) {
        const opened = await openLetterArtifact(repoId, sealed, sealed.length, ownerKeys, { identityId: hex(r, 'identityId'), secrets: [hex(r, 'priv')] })
        expect(bytesToHex(opened)).toBe(bytesToHex(plain))
      }
      // the file key is non-extractable: recompute it with @noble/hashes from its definition
      const packKey = expand(nobleSha256, hmac(nobleSha256, repoId, kObj), concat(new TextEncoder().encode('dash-forge/v2/obj-pack'), new Uint8Array([0, 2]), fileId), 32)
      const headerLen = 69 + 64 * recipients.length
      return {
        header: bytesToHex(sealed.subarray(0, headerLen)),
        packKey: bytesToHex(packKey),
        sealedLen: sealed.length,
        packHash: bytesToHex(await sha256(sealed)),
        sealed: bytesToHex(sealed),
      }
    }
    case 'named_artifact_open': {
      const repoId = hex(inp, 'repoId')
      const sealed = hex(inp, 'sealed')
      const ownerKeys: OwnerKey[] = arr(inp, 'ownerKeys').map((k) => ({ id: num(k, 'id'), purpose: num(k, 'purpose'), keyType: num(k, 'keyType'), data: hex(k, 'data') }))
      const results: Json[] = []
      for (const r of arr(inp, 'readers')) {
        const keys = r['keys']
        if (!Array.isArray(keys)) throw new TypeError('keys: expected an array')
        try {
          const pt = await openLetterArtifact(repoId, sealed, num(inp, 'sizeBytes'), ownerKeys, { identityId: hex(r, 'identityId'), secrets: keys.map((k) => hexToBytes(String(k))) })
          results.push({ plaintextHex: bytesToHex(pt) })
        } catch (e) {
          if (e instanceof ArtifactError) results.push({ error: e.code })
          else throw e
        }
      }
      return { results }
    }
    case 'named_envelope_open': {
      const repoId = hex(inp, 'repoId')
      const doc = storedDoc(obj(inp, 'doc'))
      const ownerKeys: OwnerKey[] = arr(inp, 'ownerKeys').map((k) => ({ id: num(k, 'id'), purpose: num(k, 'purpose'), keyType: num(k, 'keyType'), data: hex(k, 'data') }))
      const results: Json[] = []
      for (const r of arr(inp, 'readers')) {
        const keys = r['keys']
        if (!Array.isArray(keys)) throw new TypeError('keys: expected an array')
        const reader = { identityId: hex(r, 'identityId'), secrets: keys.map((k) => hexToBytes(String(k))) }
        results.push(letterJson(await openLetter(repoId, doc, ownerKeys, reader)))
      }
      return { results }
    }
    case 'private_doc_open': {
      const repoId = hex(inp, 'repoId')
      const d = obj(inp, 'doc')
      const ctx = await openContextOf(repoId, obj(inp, 'context'))
      const doc: StoredPrivateDoc = {
        ...toDoc(d),
        id: 'id' in d ? privateId(str(d, 'id')) : undefined,
        createdAtBlockHeight: 'createdAtBlockHeight' in d ? num(d, 'createdAtBlockHeight') : undefined,
        updatedAtBlockHeight: 'updatedAtBlockHeight' in d ? num(d, 'updatedAtBlockHeight') : undefined,
        enc: hex(d, 'enc'),
      }
      return openJson(await openContent(doc, ctx))
    }
    case 'private_pack_seal': {
      const keys = await importKey(inp)
      const plain = plaintextOf(inp)
      const sealed = await sealPackWithFileId(keys, plain, hex(inp, 'fileId'))
      const header = parseHeader(sealed)
      const nSeg = segmentCount(header.plaintextLen, header.segLog2)
      const S = 2 ** header.segLog2
      const tags = Array.from({ length: nSeg }, (_, i) => {
        const end = Math.min(36 + (i + 1) * (S + 16), sealed.length)
        return bytesToHex(sealed.subarray(end - 16, end))
      })
      const out: { [k: string]: Json } = {
        header: bytesToHex(header.raw),
        segments: nSeg,
        sealedLen: sealed.length,
        tags,
        packHash: bytesToHex(await sha256(sealed)),
        plaintextSha256: bytesToHex(await sha256(plain)),
      }
      if (isObj(v.expected) && 'sealed' in v.expected) out['sealed'] = bytesToHex(sealed)
      // The production open reads back what was sealed
      expect(bytesToHex(await openPack(sealed, sealed.length, new Map([[keys.epoch, keys]])))).toBe(bytesToHex(plain))
      return out
    }
    case 'private_pack_open': {
      const keys = await keyring(hex(inp, 'repoId'), obj(inp, 'keys'))
      return packErrorOf(async () => {
        const plain = await openPack(hex(inp, 'sealed'), num(inp, 'sizeBytes'), keys)
        return { plaintextSha256: bytesToHex(await sha256(plain)), plaintextLen: plain.length }
      })
    }
    case 'private_pack_range': {
      const seal = obj(inp, 'seal')
      const keys = await importKey(seal)
      const sealed = await sealPackWithFileId(keys, plaintextOf(seal), hex(seal, 'fileId'))
      const range = inp['range']
      if (!Array.isArray(range) || range.length !== 2) throw new TypeError('range: expected [a, b]')
      const [a, b] = range.map(Number) as [number, number]
      const fetched: [number, number][] = []
      const fetchRange = async (start: number, end: number) => {
        fetched.push([start, end])
        return sealed.subarray(start, end)
      }
      return packErrorOf(async () => {
        const plan = planRange(parseHeader(sealed), a, b)
        const source = { packHash: bytesToHex(await sha256(sealed)), copy: 'vector', sizeBytes: sealed.length, fetchRange }
        const cache = new PackHeaderCache()
        const output = await readPackRange(source, a, b, new Map([[keys.epoch, keys]]), cache)
        // Exactly the header, then exactly the planned sealed range; the header is cached once authenticated
        expect(fetched).toEqual([[0, 36], [...plan.sealedRange]])
        expect(cache.has(source.packHash, source.copy)).toBe(true)
        return { segments: [...plan.segments], sealedRange: [...plan.sealedRange], output: bytesToHex(output) }
      })
    }
    case 'private_wrap_seal': {
      const repoId = hex(inp, 'repoId')
      const epoch = num(inp, 'epoch')
      const raw = hex(inp, 'key')
      const keys = await EpochKeys.import(repoId, epoch, raw)
      const plaintext = await buildWrapPlaintext(keys, raw)
      const want = v.expected as Obj
      // The raw primitive: AES-256-CBC (PKCS#7) under the vector's shared key and IV
      const iv = hex(inp, 'iv')
      const cbcKey = await crypto.subtle.importKey('raw', hexToBytes(str(want, 'shared')), 'AES-CBC', false, ['encrypt'])
      const ct = new Uint8Array(await crypto.subtle.encrypt({ name: 'AES-CBC', iv: new Uint8Array(iv) }, cbcKey, plaintext))
      const wrapped = concat(iv, ct)
      // The SDK derives the same shared key: it opens the vector's bytes in both directions
      const anchorCommit = keys.commit
      for (const [priv, pub] of [
        [str(inp, 'recipientPriv'), str(inp, 'senderPub')],
        [str(inp, 'senderPriv'), str(inp, 'recipientPub')],
      ] as const) {
        const opened = await openVectorWrap(repoId, epoch, wrapped, priv, pub, anchorCommit)
        expect(bytesToHex(opened.commit)).toBe(bytesToHex(keys.commit))
      }
      // And the production seal round-trips through the SDK with its own IV
      const sdkWrapped = await wrapRoundTrip(inp, keys, raw)
      expect(sdkWrapped.length).toBe(64)
      expect(bytesToHex(sdkWrapped.subarray(0, 16))).not.toBe(bytesToHex(iv))
      const back = await openVectorWrap(repoId, epoch, sdkWrapped, str(inp, 'recipientPriv'), str(inp, 'senderPub'), anchorCommit)
      expect(bytesToHex(back.kcv)).toBe(bytesToHex(keys.kcv))
      return { shared: str(want, 'shared'), plaintext: bytesToHex(plaintext), wrapped: bytesToHex(wrapped) }
    }
    case 'private_wrap_open': {
      const repoId = hex(inp, 'repoId')
      const epoch = num(inp, 'epoch')
      try {
        const keys = await openVectorWrap(
          repoId,
          epoch,
          hex(inp, 'wrapped'),
          str(inp, 'readerPriv'),
          str(inp, 'counterpartyPub'),
          hex(inp, 'anchorCommit'),
        )
        // Non-extractable: identify the recovered key by its commitment and KCV instead
        const expected = v.expected as Obj
        const want = await EpochKeys.import(repoId, epoch, hexToBytes(str(expected, 'key')))
        expect(bytesToHex(keys.commit)).toBe(bytesToHex(want.commit))
        expect(bytesToHex(keys.kcv)).toBe(bytesToHex(want.kcv))
        return { key: str(expected, 'key') }
      } catch (e) {
        if (e instanceof WrapError) return { error: e.code }
        throw e
      }
    }
    case 'private_epoch':
      return runEpoch(inp)
    case 'private_release_seal':
      return releaseSeal(inp)
    case 'private_release_open':
      return releaseOpen(inp)
    case 'private_release_fold':
      return releaseFold(inp)
    case 'private_hedge': {
      const keys = await importKey(inp)
      const rnd = hex(inp, 'rnd')
      if ('doc' in inp) {
        const doc = toDoc(obj(inp, 'doc'))
        const { ad, tlv } = await sealDocWithNonce(keys, doc, toFields(obj(inp, 'fields')), new Uint8Array(12))
        expect(bytesToHex(tlv)).toBe(bytesToHex(buildTlv(toFields(obj(inp, 'fields')), { type: doc.type, epoch: doc.epoch })))
        return { nonce: bytesToHex(await hedgedNonce(keys, rnd, ad, tlv)) }
      }
      return { fileId: bytesToHex(await hedgedFileId(keys, rnd, plaintextOf(inp))) }
    }
    default:
      throw new Error(`unknown private vector case: ${v.case}`)
  }
}

// ---------------------------------------------------------------------------------------------
// Sealed releases (§16)
// ---------------------------------------------------------------------------------------------

/** The plaintext content fields a sealed release must not carry (§16.2). */
const RELEASE_PLAINTEXT = ['name', 'notes', 'assets', 'assetManifest', 'yanked', 'imported']

function releaseOpenJson(r: ReleaseOpenResult): Json {
  if (r.status === 'readable') return { status: 'readable', fields: { ...r.fields } }
  return r.status === 'unreadable' ? { status: 'unreadable', reason: r.reason } : { status: 'malformed' }
}

async function releaseSeal(inp: Obj): Promise<Json> {
  const keys = await importKey(inp)
  const ring = new Map([[keys.epoch, keys]])
  if ('manifest' in inp) {
    const manifest = obj(inp, 'manifest') as unknown as ReleaseManifest
    const { canonical, sealed } = await sealReleaseManifestWithFileId(keys, manifest, hex(inp, 'fileId'))
    // The production seal (hedged fileId) opens back to the same manifest
    const prod = await sealReleaseManifest(keys, manifest)
    expect(prod.canonical).toBe(canonical)
    const back = await openReleaseManifest(prod.sealed, prod.sealed.length, await sha256(prod.sealed), manifest.tag, manifest.notes !== undefined, ring)
    expect(back).toEqual(manifest)
    return {
      canonical,
      header: bytesToHex(sealed.subarray(0, 36)),
      sealedLen: sealed.length,
      packHash: bytesToHex(await sha256(sealed)),
      sealed: bytesToHex(sealed),
    }
  }
  const fields = obj(inp, 'fields') as unknown as ReleaseFields
  const owner = privateId(str(inp, 'ownerId'))
  try {
    const s = await sealReleaseWithNonce(keys, owner, fields, hex(inp, 'nonce'))
    expect(await releaseTagName(keys, fields.tag)).toBe(s.tagName)
    // The production seal (hedged nonce) opens back to the same fields
    const prod = await sealRelease(keys, owner, fields)
    expect(prod.tagName).toBe(s.tagName)
    expect(prod.enc.length).toBe(s.enc.length)
    const ctx: OpenContext = {
      keys: ring,
      anchors: new Map([[keys.epoch, { id: new Uint8Array(32), height: 1, statedHeight: 1 }]]),
      members: new IdSet([owner]),
    }
    const opened = await openRelease(ctx, {
      ownerId: owner,
      epoch: keys.epoch,
      tagName: prod.tagName,
      vis: 'private',
      delta: 0,
      enc: prod.enc,
      hasPlaintextContent: false,
    })
    expect(opened).toEqual({ status: 'readable', fields })
    return {
      tagHash: bytesToHex(await releaseTagHash(keys, fields.tag)),
      tagName: s.tagName,
      ad: bytesToHex(s.ad),
      tlv: bytesToHex(s.tlv),
      enc: bytesToHex(s.enc),
      props: { tagName: s.tagName, vis: 'private', delta: 0, epoch: keys.epoch, enc: bytesToHex(s.enc) },
    }
  } catch (e) {
    if (e instanceof MalformedError) return { error: 'malformed' }
    if (e instanceof TooLargeError) return { error: 'tooLarge' }
    throw e
  }
}

async function releaseOpen(inp: Obj): Promise<Json> {
  const repoId = hex(inp, 'repoId')
  if ('manifest' in inp) {
    const m = obj(inp, 'manifest')
    const ring = await keyring(repoId, obj(inp, 'keys'))
    try {
      const manifest = await openReleaseManifest(
        hex(m, 'sealed'),
        num(m, 'sizeBytes'),
        hex(m, 'assetManifest'),
        str(m, 'tag'),
        m['notesContinue'] === true,
        ring,
      )
      return { status: 'readable', manifest: manifest as unknown as Json }
    } catch (e) {
      if (e instanceof ManifestMismatchError) return { error: 'manifestMismatch' }
      if (e instanceof PackError) return { error: e.code }
      throw e
    }
  }
  const d = obj(inp, 'doc')
  const doc: StoredRelease = {
    ownerId: privateId(str(d, 'ownerId')),
    epoch: 'epoch' in d ? num(d, 'epoch') : undefined,
    tagName: str(d, 'tagName'),
    vis: str(d, 'vis'),
    delta: num(d, 'delta'),
    enc: optHex(d, 'enc'),
    hasPlaintextContent: RELEASE_PLAINTEXT.some((k) => k in d),
  }
  return releaseOpenJson(await openRelease(await openContextOf(repoId, obj(inp, 'context')), doc))
}

function releaseFold(inp: Obj): Json {
  const rows = arr(inp, 'revisions').map((r) => ({
    idHex: str(r, 'id'),
    id: hex(r, 'id'),
    createdAt: num(r, 'createdAt'),
    epoch: num(r, 'epoch'),
    tagName: str(r, 'tagName'),
    status: str(r, 'status') as ReleaseStatus,
    enc: str(r, 'enc'),
    fields: 'fields' in r ? (obj(r, 'fields') as unknown as ReleaseFields) : undefined,
  }))
  const f = foldReleases(rows)
  return {
    live: Object.fromEntries(f.live.map((r) => [r.fields?.tag ?? '', r.idHex])),
    history: f.history.map((r) => r.idHex),
    count: f.count,
    replays: f.replays.map((r) => r.idHex),
    unknownTags: f.unknownTags,
    stale: f.stale,
    hidden: f.hidden,
  }
}

async function runEpoch(inp: Obj): Promise<Json> {
  const repoId = hex(inp, 'repoId')
  const encoding: IdEncoding = 'idEncoding' in inp ? (str(inp, 'idEncoding') as IdEncoding) : 'hex'
  expect(['hex', 'base58']).toContain(encoding)
  const id = (o: Obj, k: string) => privateId(str(o, k))
  const out = (b: Uint8Array) => encodePrivateId(b, encoding)
  const memberships: PrivateMembership[] = arr(inp, 'memberships').map((m) => ({
    identity: id(m, 'identity'),
    role: str(m, 'role') as PrivateMembership['role'],
  }))
  const configs: ConfigRow[] = arr(inp, 'configs').map((c) => ({
    id: id(c, 'id'),
    owner: id(c, 'owner'),
    epoch: num(c, 'epoch'),
    createdAtBlockHeight: num(c, 'createdAtBlockHeight'),
    enc: hex(c, 'enc'),
  }))
  const wraps: WrapRow[] = []
  for (const w of arr(inp, 'wraps')) {
    const epoch = num(w, 'epoch')
    wraps.push({
      id: id(w, 'id'),
      owner: id(w, 'owner'),
      memberId: id(w, 'memberId'),
      epoch,
      recipientKeyId: num(w, 'recipientKeyId'),
      keyEnabled: w['keyEnabled'] === true,
      keys: 'key' in w ? await EpochKeys.import(repoId, epoch, hex(w, 'key')) : undefined,
    })
  }
  const r = await resolveEpochs({ repoId, reader: id(inp, 'reader'), memberships, configs, wraps })
  const result: { [k: string]: Json } = {
    currentEpoch: r.currentEpoch,
    anchors: Object.fromEntries([...r.anchors].map(([e, a]) => [String(e), out(a.id)])),
    readable: [...r.keys.keys()].sort((a, b) => a - b),
    writeEpoch: r.writeEpoch,
    unanchored: [...r.unanchored],
    alerts: r.alerts.map(
      (a): Json =>
        'author' in a
          ? { kind: a.kind, epoch: a.epoch, author: out(a.author) }
          : { kind: a.kind, epoch: a.epoch, members: a.members.map(out) },
    ),
    repair:
      r.repair === null
        ? null
        : { rotate: r.repair.rotate, nonMembers: r.repair.nonMembers.map(out), missingWraps: r.repair.missingWraps.map(out) },
  }
  if ('contentQueries' in inp) {
    result['content'] = arr(inp, 'contentQueries').map((q) =>
      contentIsLate(r, num(q, 'epoch'), num(q, 'createdAtBlockHeight'), id(q, 'owner')) ? 'late' : 'shown',
    )
  }
  if ('manifestQueries' in inp) {
    result['manifests'] = arr(inp, 'manifestQueries').map((q) => ({
      ...manifestStanding(r, num(q, 'headerEpoch'), num(q, 'createdAtBlockHeight'), id(q, 'owner')),
    }))
  }
  return result
}

// ---------------------------------------------------------------------------------------------

describe('private-repository conformance vectors', () => {
  const vectors: Vector[] = PRIVATE_FILES.map((f) => JSON.parse(readFileSync(resolve(VECTORS_DIR, f), 'utf8')) as Vector)
  let ran = 0

  beforeAll(async () => {
    evo = await import('@dashevo/evo-sdk')
    await evo.EvoSDK.getLatestVersionNumber()
    // `repoKey` is a forge-collab type (RC1 layout O-03); its gates name forge-core, whose id the
    // deploy script substitutes (any valid id parses)
    const text = readFileSync(resolve(ROOT, 'forge-contracts', 'contracts', 'forge-collab.json'), 'utf8').replaceAll(
      'FORGE_CORE_CONTRACT_ID',
      'A2KL77ngVM1ft1t1em2XKt1rWCBZANdAJMyfWrDGCcd1',
    )
    repoKeyContract = evo.DataContract.fromJSON(JSON.parse(text) as Parameters<Evo['DataContract']['fromJSON']>[0], true, 14)
    facade = new evo.EvoSDK().encryptedFor
  })

  for (const v of vectors) {
    it(`${v.case} :: ${v.name}`, async () => {
      expect(isCryptoCase(v.case)).toBe(true)
      expect(v.rules).toBe('v2')
      const shape = SHAPES[v.case]
      if (shape === undefined) throw new Error(`unknown private vector case: ${v.case}`)
      checkShape(v.input, shape, `${v.name}.input`)
      expect(await run(v)).toEqual(v.expected)
      ran++
    })
  }

  it('ran every private vector file', () => {
    expect(PRIVATE_FILES.length).toBeGreaterThanOrEqual(221)
    expect(ran).toBe(PRIVATE_FILES.length)
  })
})
