//! The RC1 conformance validator: judge a document against the generated RC1 contracts the
//! way a client pre-check and a node's basic validation judge a create.
//!
//! The contracts are `forge-contracts/contracts/{forge-core,forge-collab,forge-community}.json`
//! (generated by `forge-contracts/schema/build.py`), read from the source tree and parsed once
//! with full validation under protocol 14 by the SDK's own rs-dpp (`validation` +
//! `json-conversion`). Each gets the id the deploy script derives (owner 0x07×32, nonce
//! 1/2/3) and the ids of the earlier contracts substituted for their placeholders
//! (`FORGE_CORE_CONTRACT_ID`, `FORGE_COLLAB_CONTRACT_ID`), as `tools/contract-validate` does.
//!
//! A document is judged by the create's structure checks that read the document and its signer
//! alone, in the order drive-abci's `advanced_structure_v1` runs them:
//! - `validate_document_properties`: the JSON schema, `maxBytes`, and every
//!   `propertyConstraints` rule that reads no total, time or height;
//! - `validate_distinct_from_properties` (10419, `distinctFrom`);
//! - `validate_encrypted_property_shapes` (10420, an `encryptedFor` ciphertext's shape);
//! - `first_unrevealable_lookup_key` (10423; the RC1 contracts have no computed keys).
//!
//! The rules that read a total, the block or another document (dense, c1..c6, lockGate,
//! platformChunks, oneLive, atMost20, notFuture, every `refersTo` / `where` / `findBy`
//! reference) are consensus's, covered by the live suite (`forge-contracts/scripts/rc1-live.mjs`).
//!
//! [`validate_props`] is the entry point; [`assert_valid`] / [`assert_refused`] /
//! [`first_error`] are conveniences for builder tests signed by [`OWNER`]. The `vectors` tests
//! run every case in `forge-contracts/vectors/rc1/`; the `builders` tests run the Rust builders.

use std::collections::BTreeMap;
use std::sync::OnceLock;

use dpp::consensus::basic::document::DocumentReferencePreimageInvalidError;
use dpp::consensus::basic::BasicError;
use dpp::consensus::codes::ErrorWithCode;
use dpp::consensus::ConsensusError;
use dpp::data_contract::accessors::v0::DataContractV0Getters;
use dpp::data_contract::conversion::json::DataContractJsonConversionMethodsV0;
use dpp::data_contract::document_type::first_unrevealable_lookup_key;
use dpp::data_contract::document_type::methods::{DocumentTypeBasicMethods, DocumentTypeV0Methods};
use dpp::data_contract::document_type::property_constraints::DocumentSystemValues;
use dpp::data_contract::validate_document::DataContractDocumentValidationMethodsV0;
use dpp::data_contract::DataContract;
use dpp::identifier::Identifier;
use dpp::platform_value::string_encoding::Encoding;
use dpp::platform_value::Value;
use dpp::validation::SimpleConsensusValidationResult;
use dpp::version::PlatformVersion;
use serde_json::Value as Json;

use crate::layout::ForgeContract;
use crate::platform::FieldValue;

/// The protocol the RC1 contracts are registered under (Platform v4.2, protocol 14).
const PROTOCOL_VERSION: u32 = 14;

/// The contracts' placeholder owner, and the signer the convenience helpers judge as.
pub const OWNER: [u8; 32] = [7u8; 32];

/// The generated contracts, in registration order (a later one refers to the earlier ones).
const CONTRACTS: [ForgeContract; 3] = [
    ForgeContract::Core,
    ForgeContract::Collab,
    ForgeContract::Community,
];

fn root() -> &'static str {
    concat!(env!("CARGO_MANIFEST_DIR"), "/../../forge-contracts")
}

fn platform_version() -> &'static PlatformVersion {
    PlatformVersion::get(PROTOCOL_VERSION).expect("protocol 14 is known to rs-dpp")
}

/// `forge-core` -> `FORGE_CORE_CONTRACT_ID`.
fn placeholder_for(name: &str) -> String {
    format!("{}_CONTRACT_ID", name.to_uppercase().replace('-', "_"))
}

/// The three contracts, parsed once, indexed as [`CONTRACTS`].
fn contracts() -> &'static [DataContract; 3] {
    static PARSED: OnceLock<[DataContract; 3]> = OnceLock::new();
    PARSED.get_or_init(|| {
        let owner = Identifier::from(OWNER);
        let pv = platform_version();
        let mut placeholders: Vec<(String, String)> = Vec::new();
        CONTRACTS.map(|c| {
            let name = c.name();
            let path = format!("{}/contracts/{name}.json", root());
            let mut text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{path}: {e}"));
            for (placeholder, id) in &placeholders {
                text = text.replace(placeholder, id);
            }
            assert!(
                !text.contains("_CONTRACT_ID\""),
                "{name}: an id placeholder is left unresolved"
            );
            let mut json: Json = serde_json::from_str(&text).expect("contract JSON");
            let nonce = placeholders.len() as u64 + 1;
            let id = DataContract::generate_data_contract_id_v0(owner, nonce);
            json["id"] = Json::String(id.to_string(Encoding::Base58));
            json["ownerId"] = Json::String(owner.to_string(Encoding::Base58));
            let contract = DataContract::from_json(json, true, pv)
                .unwrap_or_else(|e| panic!("{name} fails full validation: {e}"));
            placeholders.push((placeholder_for(name), id.to_string(Encoding::Base58)));
            contract
        })
    })
}

/// A generated contract as the client loads it: for tests of what the client reads off a
/// contract's shape (the RC2 build flags).
#[cfg(test)]
pub(crate) fn loaded(c: ForgeContract) -> crate::platform::LoadedContract {
    let i = CONTRACTS
        .iter()
        .position(|x| *x == c)
        .expect("a forge contract");
    crate::platform::LoadedContract::for_tests(contracts()[i].clone())
}

/// A refusal's reason as the vectors name it: the JSON Schema keyword, the broken
/// `propertyConstraints` rule, `maxBytes`, or else the consensus error code (b7gate's and
/// contract-validate's `reason`).
fn reason(e: &ConsensusError) -> String {
    match e {
        ConsensusError::BasicError(BasicError::JsonSchemaError(j)) => j.keyword().to_string(),
        ConsensusError::BasicError(BasicError::DocumentPropertyConstraintViolatedError(c)) => {
            c.constraint().to_string()
        }
        ConsensusError::BasicError(BasicError::DocumentPropertyMaxBytesExceededError(_)) => {
            "maxBytes".to_string()
        }
        other => other.code().to_string(),
    }
}

/// Judge `data` as a create of `doc_type` signed by `signer`, running the structure checks a
/// node runs in `advanced_structure_v1` that need no state: `None` when RC1 accepts it, else
/// the first error as `(reason, message)`.
fn judge(
    doc_type: &str,
    data: &BTreeMap<String, Value>,
    signer: Identifier,
) -> Option<(String, String)> {
    let Some(contract) = ForgeContract::of(doc_type) else {
        return Some((
            "documentType".to_string(),
            format!("`{doc_type}` is not an RC1 document type"),
        ));
    };
    let i = CONTRACTS
        .iter()
        .position(|c| *c == contract)
        .expect("listed");
    let contract = &contracts()[i];
    let pv = platform_version();
    let ran = |r: Result<SimpleConsensusValidationResult, _>| {
        r.unwrap_or_else(|e| panic!("{doc_type}: validation could not run: {e}"))
    };
    let document_type = contract
        .document_type_for_name(doc_type)
        .unwrap_or_else(|e| panic!("{doc_type}: {e}"));
    let first =
        |r: SimpleConsensusValidationResult| r.errors.first().map(|e| (reason(e), e.to_string()));
    let system = DocumentSystemValues::owned_by(signer);
    first(ran(contract.validate_document_properties(
        doc_type,
        data.clone().into(),
        &system,
        pv,
    )))
    .or_else(|| {
        first(ran(
            document_type.validate_distinct_from_properties(data, signer, pv)
        ))
    })
    .or_else(|| {
        first(ran(
            document_type.validate_encrypted_property_shapes(data, pv)
        ))
    })
    .or_else(|| {
        first_unrevealable_lookup_key(document_type, data, signer).map(|(path, e)| {
            let e: ConsensusError = DocumentReferencePreimageInvalidError::new(
                doc_type.to_string(),
                path,
                e.param,
                e.reason,
            )
            .into();
            (reason(&e), e.to_string())
        })
    })
}

fn judge_props(
    doc_type: &str,
    props: &BTreeMap<String, FieldValue>,
    owner: [u8; 32],
) -> Option<(String, String)> {
    let data = props
        .iter()
        .map(|(k, v)| (k.clone(), v.clone().into_value()))
        .collect();
    judge(doc_type, &data, Identifier::from(owner))
}

/// Judge `props` as a create of `doc_type` signed by `owner`. `Err("<reason>: <message>")` for
/// the first error: `<reason>` is what the vectors' `why` names (a JSON Schema keyword, a
/// `propertyConstraints` rule name, `maxBytes`, or a consensus error code; `documentType` for a
/// type RC1 does not define), `<message>` rs-dpp's text.
pub fn validate_props(
    doc_type: &str,
    props: &BTreeMap<String, FieldValue>,
    owner: [u8; 32],
) -> Result<(), String> {
    match judge_props(doc_type, props, owner) {
        None => Ok(()),
        Some((why, message)) => Err(format!("{why}: {message}")),
    }
}

/// The reason RC1 refuses these properties for a `doc_type` create by [`OWNER`], or `None` when
/// it accepts them.
pub fn first_error(doc_type: &str, props: &BTreeMap<String, FieldValue>) -> Option<String> {
    judge_props(doc_type, props, OWNER).map(|(why, _)| why)
}

/// Panic unless RC1 accepts these properties for a `doc_type` create by [`OWNER`].
#[track_caller]
pub fn assert_valid(doc_type: &str, props: &BTreeMap<String, FieldValue>) {
    if let Err(e) = validate_props(doc_type, props, OWNER) {
        panic!("RC1 refuses this {doc_type}: {e}\n  properties: {props:?}");
    }
}

/// Panic unless RC1 refuses these properties for a `doc_type` create by [`OWNER`], first for
/// `why`.
#[track_caller]
pub fn assert_refused(doc_type: &str, props: &BTreeMap<String, FieldValue>, why: &str) {
    match judge_props(doc_type, props, OWNER) {
        None => panic!("RC1 accepts this {doc_type}, want {why}\n  properties: {props:?}"),
        Some((got, message)) => assert_eq!(got, why, "{doc_type}: {message}"),
    }
}

#[cfg(test)]
mod vectors {
    use super::*;

    /// The committed vector sets (`forge-contracts/schema/vectors.py`) and a floor on how many
    /// cases each holds: the sets only grow, so a smaller one means a file went missing or was
    /// cut. Every case is judged here: `vectors.py` keeps the checks that read a total, the block
    /// or another document (its `LIVE_ONLY` list) out of the sets, for
    /// `forge-contracts/scripts/rc1-live.mjs`. RC2's fused star (build.py `fused_star`) drops
    /// starBeat and its 6 community cases.
    const SETS: [(&str, usize); 3] = [
        ("forge-core", 171),
        ("forge-collab", 101),
        ("forge-community", 111),
    ];

    /// An identifier written as a byte `n` (32 bytes of n) or a base58 string.
    fn identifier(j: &Json) -> Identifier {
        match j {
            Json::Number(n) => {
                let n = n
                    .as_u64()
                    .and_then(|n| u8::try_from(n).ok())
                    .expect("an id byte");
                Identifier::from([n; 32])
            }
            Json::String(s) => {
                Identifier::from_string(s, Encoding::Base58).unwrap_or_else(|e| panic!("{s}: {e}"))
            }
            other => panic!("an identifier is a byte or a base58 string, not {other}"),
        }
    }

    /// A vector document (the README's format): `{"$id": n | "<base58>"}` is an identifier,
    /// `{"$b": [fill, len]}` is `len` bytes of `fill` and `{"$hex": "…"}` is bytes.
    fn doc_data(j: &Json) -> BTreeMap<String, Value> {
        j.as_object()
            .expect("a vector document is an object")
            .iter()
            .map(|(k, v)| (k.clone(), doc_value(v)))
            .collect()
    }

    fn doc_value(j: &Json) -> Value {
        match j {
            Json::Object(m) if m.contains_key("$b") => {
                let a = m["$b"].as_array().expect("$b: [fill, len]");
                let fill = u8::try_from(a[0].as_u64().expect("fill")).expect("fill is a byte");
                let len = usize::try_from(a[1].as_u64().expect("len")).expect("len");
                Value::Bytes(vec![fill; len])
            }
            Json::Object(m) if m.contains_key("$hex") => {
                let h = m["$hex"].as_str().expect("$hex is a string");
                Value::Bytes(hex::decode(h).unwrap_or_else(|e| panic!("{h}: {e}")))
            }
            Json::Object(m) if m.contains_key("$id") => {
                Value::Identifier(identifier(&m["$id"]).to_buffer())
            }
            Json::Object(m) => Value::Map(
                m.iter()
                    .map(|(k, v)| (Value::Text(k.clone()), doc_value(v)))
                    .collect(),
            ),
            Json::Array(a) => Value::Array(a.iter().map(doc_value).collect()),
            other => other.clone().into(),
        }
    }

    #[test]
    fn every_rc1_vector_is_judged_as_the_vectors_say() {
        let mut judged = Vec::new();
        let mut failures = Vec::new();
        for (set, floor) in SETS {
            let path = format!("{}/vectors/rc1/{set}.json", root());
            let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{path}: {e}"));
            let cases: Vec<Json> = serde_json::from_str(&text).expect("vector JSON");
            assert!(
                cases.len() >= floor,
                "{set}: {} cases, fewer than the {floor} committed before",
                cases.len()
            );
            judged.push(format!("{set} {}", cases.len()));
            for c in &cases {
                let ty = c["type"].as_str().expect("type");
                let name = c["name"].as_str().expect("name");
                let expect = c["expect"].as_str().expect("expect");
                assert_eq!(
                    ForgeContract::of(ty).map(ForgeContract::name),
                    Some(set),
                    "{set}: `{name}` is a {ty}, held by another contract"
                );
                let signer = c.get("owner").map_or(Identifier::from(OWNER), identifier);
                let got = judge(ty, &doc_data(&c["doc"]), signer);
                let verdict = match (expect, &got) {
                    ("ok", None) => None,
                    ("ok", Some((why, msg))) => {
                        Some(format!("accept wanted, refused [{why}] {msg}"))
                    }
                    ("refused", None) => Some("refusal wanted, accepted".to_string()),
                    ("refused", Some((why, msg))) => {
                        let want = c["why"].as_str().expect("a refused case names its why");
                        (why != want).then(|| format!("refused for [{why}], want [{want}]: {msg}"))
                    }
                    (other, _) => Some(format!("unknown expect `{other}`")),
                };
                if let Some(v) = verdict {
                    failures.push(format!("{set} / {ty} / {name}: {v}"));
                }
            }
        }
        assert!(
            failures.is_empty(),
            "{} RC1 vectors disagree (judged: {}):\n{}",
            failures.len(),
            judged.join(", "),
            failures.join("\n")
        );
    }

    #[test]
    fn the_helpers_judge_field_values() {
        let mut topic = BTreeMap::new();
        topic.insert("repoId".to_string(), FieldValue::Identifier([1; 32]));
        topic.insert("name".to_string(), FieldValue::text("web-dev"));
        topic.insert("vis".to_string(), FieldValue::text("public"));
        assert_valid("topic", &topic);
        assert_eq!(first_error("topic", &topic), None);
        topic.insert("vis".to_string(), FieldValue::text("private"));
        assert_refused("topic", &topic, "enum");
        assert_eq!(first_error("topic", &topic).as_deref(), Some("enum"));
        let e = validate_props("topic", &topic, OWNER).unwrap_err();
        assert!(e.starts_with("enum: "), "{e}");
        assert!(validate_props("manifestPart", &topic, OWNER)
            .unwrap_err()
            .starts_with("documentType: "));
    }

    /// The signer matters: a member enrols itself without `consentBy`, the owner may not.
    #[test]
    fn validate_props_judges_as_the_given_signer() {
        let member = BTreeMap::from([
            ("repoId".to_string(), FieldValue::Identifier([1; 32])),
            ("memberId".to_string(), FieldValue::Identifier([9; 32])),
            ("vis".to_string(), FieldValue::text("public")),
        ]);
        assert_eq!(validate_props("maintainer", &member, [9; 32]), Ok(()));
        let e = validate_props("maintainer", &member, OWNER).unwrap_err();
        assert!(e.starts_with("ownerOrConsented: "), "{e}");
    }
}

/// The Rust builders against RC1. Each test builds a document the way its writer does: the
/// builder's properties, `repoId` (which the service adds), then the service's stamp
/// ([`stamped`], mirroring `Collab::stamp`: `vis` by [`crate::layout::stamp_vis_for`] and, on
/// an issue, PR, comment or review by a member, `asMember` = the signer).
///
/// A test `#[ignore]`d with `RC1: …` names what the builder still lacks. Builders that are not
/// pure functions (member enrol and consent, runner enrol, topic reconcile: their properties
/// are built inside an async service method) are covered, by type, by forge-web's writer tests
/// (`lib/repo/rc1-writers.test.ts`) and the seeds' offline run
/// (`forge-contracts/scripts/seed-offline.mjs`), and by the live suite.
#[cfg(test)]
mod builders {
    use super::*;
    use crate::ci::CheckReport;
    use crate::collab::private::seal_props;
    use crate::collab::v2::{
        comment_props, event_payload_props, issue_props, patch_props, policy_props, review_props,
        transition_props, EventPayload, PatchInput, Provenance, Target, TargetKind,
    };
    use crate::collab::{CommentAnchor, Imported};
    use crate::layout::{stamp_vis_for, AS_MEMBER, MEMBER_PROOF_TYPES};
    use crate::private::{DocKind, EpochKey, EpochKeys};
    use crate::rules::v2::{next_transition, Actor, Policy, StateAction, Visibility};
    use crate::rules::{EventKind, Verdict};

    const REPO: [u8; 32] = [1; 32];
    /// A base58 document / identity id for the builders' string inputs.
    const ID: &str = "A2KL77ngVM1ft1t1em2XKt1rWCBZANdAJMyfWrDGCcd1";

    /// Who signs: a maintainer/writer of the repository, or anyone else.
    #[derive(Clone, Copy, PartialEq, Eq)]
    enum By {
        Member,
        Other,
    }

    /// The signer (0x07×32) in base58.
    fn signer() -> String {
        crate::platform::encode_identifier(OWNER)
    }

    /// `props` of `doc_type` as written to a repository of `visibility` by `by`: `repoId`, the
    /// `vis` stamp, and `asMember` when a member signs a type that carries it (never on a
    /// non-member's verdict 4/5). The pure part of `Collab::stamp`.
    fn stamped(
        doc_type: &str,
        mut props: BTreeMap<String, FieldValue>,
        visibility: Visibility,
        by: By,
    ) -> BTreeMap<String, FieldValue> {
        props = scoped(props);
        stamp_vis_for(doc_type, &mut props, visibility);
        let non_member_verdict = props
            .get("verdict")
            .and_then(FieldValue::as_u64)
            .map(Verdict::from_code)
            .is_some_and(|v| {
                matches!(
                    v,
                    Verdict::ApproveNonMember | Verdict::RequestChangesNonMember
                )
            });
        if by == By::Member && MEMBER_PROOF_TYPES.contains(&doc_type) && !non_member_verdict {
            props.insert(AS_MEMBER.to_string(), FieldValue::identifier(OWNER));
        }
        props
    }

    fn public(doc_type: &str, props: BTreeMap<String, FieldValue>, by: By) {
        assert_valid(doc_type, &stamped(doc_type, props, Visibility::Public, by));
    }

    /// Seal `props` as a private repository's `kind` document, stamp it, and check RC1 accepts it.
    fn private(doc_type: &str, kind: DocKind, props: BTreeMap<String, FieldValue>, by: By) {
        let keys = EpochKeys::derive(&REPO, 0, &EpochKey::from_bytes([3; 32]));
        let sealed = seal_props(&keys, kind, OWNER, props).unwrap();
        assert_valid(
            doc_type,
            &stamped(doc_type, sealed, Visibility::Private, by),
        );
    }

    /// `props` with `repoId` (a type that carries no `vis` or `asMember`).
    fn scoped(mut props: BTreeMap<String, FieldValue>) -> BTreeMap<String, FieldValue> {
        props.insert("repoId".to_string(), FieldValue::identifier(REPO));
        props
    }

    fn imported() -> Imported {
        Imported {
            author: "octocat".into(),
            created_at: 1_600_000_000,
            url: "https://github.com/o/r/issues/1".into(),
        }
    }

    fn target(kind: TargetKind) -> Target {
        Target {
            kind,
            id: ID.into(),
            number: 7,
            author: signer(),
        }
    }

    fn patch_input() -> PatchInput {
        PatchInput {
            title: "A fix".into(),
            body: "body".into(),
            base_ref_name: "refs/heads/main".into(),
            source_repo_id: ID.into(),
            source_ref_name: Some("refs/heads/fix".into()),
            head_oid: vec![0xab; 20],
            patch_manifest_hash: Some([4; 32]),
            draft: false,
        }
    }

    // ---------------- issue / patch ----------------

    #[test]
    fn issues_are_rc1_valid() {
        for by in [By::Member, By::Other] {
            public(
                "issue",
                issue_props(1, "A bug", "text", Provenance::default()).unwrap(),
                by,
            );
            public(
                "issue",
                issue_props(2, "t", "", Provenance::default()).unwrap(),
                by,
            );
        }
        let p = issue_props(1, "A bug", "text", Provenance::default()).unwrap();
        private("issue", DocKind::Issue, p, By::Member);
    }

    #[test]
    fn an_imported_issue_is_rc1_valid_from_a_member_only() {
        let imp = imported();
        let from = Provenance {
            imported: Some(&imp),
            upstream_number: Some(7761),
        };
        let p = issue_props(1, "A bug", "text", from).unwrap();
        public("issue", p.clone(), By::Member);
        // The contract's side of it: an import without the proof is refused. (Collab never
        // writes this: its stamp refuses a non-member's import before signing.)
        let unproved = stamped("issue", p, Visibility::Public, By::Other);
        assert_refused("issue", &unproved, "i_provenance");
    }

    #[test]
    fn patches_are_rc1_valid() {
        let bare = PatchInput {
            body: String::new(),
            source_ref_name: None,
            patch_manifest_hash: None,
            head_oid: vec![0xcd; 32],
            ..patch_input()
        };
        for by in [By::Member, By::Other] {
            public(
                "patch",
                patch_props(2, &patch_input(), Provenance::default()).unwrap(),
                by,
            );
            public(
                "patch",
                patch_props(3, &bare, Provenance::default()).unwrap(),
                by,
            );
        }
        let p = patch_props(2, &patch_input(), Provenance::default()).unwrap();
        private("patch", DocKind::Patch, p, By::Member);
    }

    #[test]
    fn an_imported_patch_is_rc1_valid_from_a_member() {
        let imp = imported();
        let from = Provenance {
            imported: Some(&imp),
            upstream_number: Some(12),
        };
        public(
            "patch",
            patch_props(2, &patch_input(), from).unwrap(),
            By::Member,
        );
    }

    // ---------------- comment / review ----------------

    #[test]
    fn comments_are_rc1_valid() {
        let inline = CommentAnchor {
            reply_to: None,
            commit_oid: Some(vec![0xab; 20]),
            path: Some("src/lib.rs".into()),
            line: Some(12),
            side: Some(1),
            start_line: Some(10),
            review_id: Some(ID.into()),
            diff_hunk: None,
        };
        let reply = CommentAnchor {
            reply_to: Some(ID.into()),
            ..CommentAnchor::default()
        };
        for by in [By::Member, By::Other] {
            public("comment", comment_props(ID, "hi", None, None).unwrap(), by);
            public(
                "comment",
                comment_props(ID, "nit", Some(&inline), None).unwrap(),
                by,
            );
            let p = comment_props(ID, "agreed", Some(&reply), None).unwrap();
            assert!(!p.contains_key("noParent"), "noParent is never set");
            public("comment", p, by);
        }
        let p = comment_props(ID, "secret", None, None).unwrap();
        private("comment", DocKind::Comment, p, By::Other);
    }

    #[test]
    fn an_imported_comment_is_rc1_valid_from_a_member() {
        let p = comment_props(ID, "hi", None, Some(&imported())).unwrap();
        public("comment", p, By::Member);
    }

    /// QW2-010: a mirrored review comment keeps its source hunk; one too big or off a file is
    /// refused before signing.
    #[test]
    fn an_imported_review_comment_with_a_hunk_is_rc1_valid() {
        let mut a = CommentAnchor {
            commit_oid: Some(vec![0xab; 20]),
            path: Some("src/lib.rs".into()),
            line: Some(12),
            side: Some(1),
            diff_hunk: Some("@@ -10,2 +10,3 @@\n a\n+b\n c".into()),
            ..CommentAnchor::default()
        };
        let p = comment_props(ID, "nit", Some(&a), Some(&imported())).unwrap();
        assert!(p.contains_key("diffHunk"));
        public("comment", p, By::Member);
        a.diff_hunk = Some(format!("@@ -1 +1 @@\n+{}", "é".repeat(600)));
        assert!(comment_props(ID, "nit", Some(&a), Some(&imported())).is_err());
        a.diff_hunk = Some("@@ -1 +1 @@".into());
        a.path = None;
        assert!(comment_props(ID, "nit", Some(&a), Some(&imported())).is_err());
    }

    #[test]
    fn reviews_are_rc1_valid_with_the_verdict_their_signer_writes() {
        for (by, member) in [(By::Member, true), (By::Other, false)] {
            for v in [Verdict::Approve, Verdict::RequestChanges, Verdict::Comment] {
                let v = v.as_written_by(member);
                let p = review_props(ID, v, &[0xab; 20], "lgtm", Some(2), None).unwrap();
                public("review", p, by);
            }
        }
        let p = review_props(ID, Verdict::Comment, &[0xab; 20], "", None, None).unwrap();
        private("review", DocKind::Review, p, By::Member);
        // A member's verdict needs the proof (the contract's side: Collab writes a non-member's
        // approval as verdict 4, never as an unproved 1).
        let p = review_props(ID, Verdict::Approve, &[0xab; 20], "", None, None).unwrap();
        let unproved = stamped("review", p, Visibility::Public, By::Other);
        assert_refused("review", &unproved, "memberVerdict");
    }

    #[test]
    fn an_imported_review_is_rc1_valid() {
        let p = review_props(
            ID,
            Verdict::Approve,
            &[0xab; 20],
            "x",
            None,
            Some(&imported()),
        )
        .unwrap();
        public("review", p, By::Member);
    }

    // ---------------- transition / event / policy ----------------

    #[test]
    fn every_transition_move_is_rc1_valid() {
        use StateAction::{Close, Draft, Lock, Merge, Ready, Reopen, Unlock};
        let moves: [(TargetKind, i64, StateAction); 13] = [
            (TargetKind::Issue, 0, Close),
            (TargetKind::Issue, 1, Reopen),
            (TargetKind::Issue, 1, Lock),
            (TargetKind::Issue, 16, Unlock),
            (TargetKind::Patch, 0, Close),
            (TargetKind::Patch, 1, Reopen),
            (TargetKind::Patch, 0, Merge),
            (TargetKind::Patch, 0, Draft),
            (TargetKind::Patch, 8, Ready),
            (TargetKind::Patch, 8, Close),
            (TargetKind::Patch, 9, Reopen),
            (TargetKind::Patch, 2, Lock),
            (TargetKind::Patch, 18, Unlock),
        ];
        for (kind, sum, action) in moves {
            let t = target(kind);
            let mut written = 0;
            for actor in [Actor::Member, Actor::Author] {
                let Some(mv) =
                    next_transition(kind.transition_target(), sum, action, actor, t.number)
                else {
                    continue;
                };
                let oid = (action == Merge).then_some(&[0xaa; 20][..]);
                assert_valid(
                    "transition",
                    &scoped(transition_props(&t, &mv, oid).unwrap()),
                );
                written += 1;
            }
            // Only a member merges, locks and unlocks; the author may make every other move.
            let member_only = matches!(action, Merge | Lock | Unlock);
            assert_eq!(
                written,
                if member_only { 1 } else { 2 },
                "{kind:?} {action:?}"
            );
        }
    }

    #[test]
    fn every_event_kind_is_rc1_valid() {
        let issue = target(TargetKind::Issue);
        let pr = target(TargetKind::Patch);
        let v = |value| EventPayload {
            value: Some(value),
            ..EventPayload::default()
        };
        let r = EventPayload {
            ref_id: Some(ID),
            ..EventPayload::default()
        };
        let who = signer();
        let assignee = EventPayload {
            value: Some(&who),
            ref_id: Some(&who),
            ..EventPayload::default()
        };
        let head = EventPayload {
            oid: Some(&[0xab; 20]),
            ..EventPayload::default()
        };
        let none = EventPayload::default();
        let cases: [(&Target, EventKind, &EventPayload<'_>); 15] = [
            (&issue, EventKind::LabelAdd, &v("bug")),
            (&issue, EventKind::LabelRemove, &v("bug")),
            (&issue, EventKind::Assign, &assignee),
            (&issue, EventKind::Unassign, &assignee),
            (&pr, EventKind::Retarget, &v("refs/heads/dev")),
            (&pr, EventKind::ThreadResolve, &r),
            (&pr, EventKind::ThreadUnresolve, &r),
            (&pr, EventKind::ReviewRequest, &r),
            (&pr, EventKind::ReviewRequestRemove, &r),
            (&pr, EventKind::ReviewDismiss, &r),
            (&pr, EventKind::HeadUpdate, &head),
            (&issue, EventKind::MilestoneSet, &v("v1")),
            (&issue, EventKind::MilestoneClear, &none),
            (&issue, EventKind::Pin, &none),
            (&issue, EventKind::Unpin, &none),
        ];
        for (t, kind, payload) in cases {
            let p = scoped(event_payload_props(t, kind, payload).unwrap());
            assert_valid("event", &p);
            if crate::rules::v2::is_author_kind(kind) {
                assert_valid("authorEvent", &p);
            }
        }
        // Lock and unlock are transitions in RC1 (the event kinds 21/22 break `noState`).
        for kind in [EventKind::Lock, EventKind::Unlock] {
            assert!(
                event_payload_props(&issue, kind, &none).is_err(),
                "{kind:?}"
            );
        }
    }

    /// RC2 MOD: a hide or unhide as `Collab::set_hidden` writes it (the writer's own
    /// `asMaintainer` where the contract has it) is accepted; without the proof, or naming
    /// someone else, `hideByMaint` refuses it. A reason off the list, or one on an unhide, is
    /// refused before signing.
    #[test]
    fn hides_are_rc1_valid_with_the_writers_maintainer_proof() {
        use crate::collab::moderation::EVENT_AS_MAINTAINER;
        let issue = target(TargetKind::Issue);
        let pr = target(TargetKind::Patch);
        let proved = super::loaded(crate::layout::ForgeContract::Community)
            .has_property("event", EVENT_AS_MAINTAINER);
        assert!(proved, "the committed forge-community carries RC2 MOD");
        let hide = |t: &Target, kind: EventKind, item: Option<&str>, reason: Option<&str>| {
            scoped(
                event_payload_props(
                    t,
                    kind,
                    &EventPayload {
                        value: reason,
                        ref_id: item,
                        ..EventPayload::default()
                    },
                )
                .unwrap(),
            )
        };
        for (t, kind, item, reason) in [
            (&issue, EventKind::Hide, Some(ID), Some("spam")),
            (&issue, EventKind::Hide, None, Some("off-topic")),
            (&pr, EventKind::Hide, Some(ID), None),
            (&pr, EventKind::Unhide, Some(ID), None),
        ] {
            let mut p = hide(t, kind, item, reason);
            if proved {
                assert_refused("event", &p, "hideByMaint");
                p.insert(EVENT_AS_MAINTAINER.into(), FieldValue::identifier([9; 32]));
                assert_refused("event", &p, "hideByMaint");
                p.insert(EVENT_AS_MAINTAINER.into(), FieldValue::identifier(OWNER));
            }
            assert_valid("event", &p);
        }
        let none = EventPayload::default();
        let rude = EventPayload {
            value: Some("rude"),
            ..EventPayload::default()
        };
        assert!(event_payload_props(&issue, EventKind::Hide, &rude).is_err());
        let spam = EventPayload {
            value: Some("spam"),
            ..EventPayload::default()
        };
        assert!(event_payload_props(&issue, EventKind::Unhide, &spam).is_err());
        assert!(event_payload_props(&issue, EventKind::Unhide, &none).is_ok());
    }

    #[test]
    fn a_policy_is_rc1_valid() {
        let p = policy_props(&Policy {
            required_approvals: 2,
            approver_role: 1,
            require_checks: true,
            merge_methods: 15,
            ..Policy::default()
        })
        .unwrap();
        assert_valid("policy", &scoped(p));
        // Required checks pinned to their sources (check_sources), and names alone.
        let pinned = Policy {
            required_approvals: 1,
            require_checks: true,
            required_checks: vec!["build".into(), "lint".into()],
            required_check_sources: vec![ID.into(), signer()],
            ..Policy::default()
        };
        assert_valid("policy", &scoped(policy_props(&pinned).unwrap()));
        let names_only = Policy {
            required_check_sources: vec![],
            ..pinned
        };
        assert_valid("policy", &scoped(policy_props(&names_only).unwrap()));
    }

    // ---------------- checkRun ----------------

    fn check_report(status: &str, conclusion: Option<&str>) -> CheckReport {
        CheckReport {
            head_oid: "ab".repeat(20),
            name: "build".into(),
            status: status.into(),
            conclusion: conclusion.map(str::to_string),
            details_url: Some("https://ci.example.com/run/1".into()),
            summary: Some("ok".into()),
            external_id: Some("gh-1".into()),
            ..CheckReport::default()
        }
    }

    #[test]
    fn check_run_creates_are_rc1_valid() {
        for (status, conclusion) in [
            ("queued", None),
            ("in_progress", None),
            ("completed", Some("success")),
            ("completed", Some("failure")),
            ("completed", Some("skipped")),
        ] {
            let mut report = check_report(status, conclusion);
            report.log = Some(("ipfs://bafy1".into(), [7; 32]));
            for visibility in [Visibility::Public, Visibility::Private] {
                // A private repository's run drops its text (privateNoText).
                let (report, _) = report.for_visibility(visibility);
                let oid = report.validate().unwrap();
                let w = report.write(None, 1_760_000_000_000).unwrap();
                let p = report.create_props(oid, &w, visibility);
                let doc = scoped(p.clone());
                assert_valid("checkRun", &doc);
                // The builder stamps vis itself.
                assert_eq!(stamped("checkRun", p, visibility, By::Other), doc);
            }
        }
        // Text on a private run is what the contract refuses: the builder never writes it.
        let report = check_report("completed", Some("success"));
        let oid = report.validate().unwrap();
        let w = report.write(None, 1_760_000_000_000).unwrap();
        let p = scoped(report.create_props(oid, &w, Visibility::Private));
        assert_refused("checkRun", &p, "privateNoText");
    }

    #[test]
    fn a_check_run_replace_stays_rc1_valid() {
        // queued → in_progress → completed, each replace merged over the stored document.
        let mut doc = BTreeMap::new();
        let mut stored: Option<crate::platform::FetchedDocument> = None;
        for (i, (status, conclusion)) in [
            ("queued", None),
            ("in_progress", None),
            ("completed", Some("failure")),
        ]
        .into_iter()
        .enumerate()
        {
            let report = check_report(status, conclusion);
            let now = 1_760_000_000_000 + i as u64 * 1000;
            let w = report.write(stored.as_ref(), now).unwrap();
            if stored.is_none() {
                doc =
                    scoped(report.create_props(report.validate().unwrap(), &w, Visibility::Public));
            } else {
                for (k, v) in report.changes(&w) {
                    if let Some(v) = v {
                        doc.insert(k, v);
                    }
                }
            }
            assert_valid("checkRun", &doc);
            stored = Some(crate::platform::FetchedDocument {
                id: "run".into(),
                owner_id: signer(),
                created_at: Some(1),
                created_at_block_height: None,
                updated_at_block_height: None,
                fields: doc.clone(),
                revision: Some(1),
            });
        }
        assert_eq!(doc.get("outcome"), Some(&FieldValue::integer(2)));
    }

    // ---------------- webhook and repoKey: ciphertext to another identity's key ----------------

    /// The signer's and the other party's ENCRYPTION private keys.
    const SENDER_KEY: [u8; 32] = [0x21; 32];
    const RECIPIENT_KEY: [u8; 32] = [0x42; 32];

    #[test]
    fn a_webhook_is_rc1_valid() {
        use crate::envelope::{self, PrivateKey, SecretBytes};
        use crate::webhooks::{hook_id_for_label, webhook_props, NewWebhook};
        let sender = PrivateKey::from_slice(&SENDER_KEY).unwrap();
        let relay = PrivateKey::from_slice(&RECIPIENT_KEY).unwrap();
        // The secret is encrypted as `WebhookService::prepare` does (encryptedFor's shape, 10420).
        let ciphertext = envelope::encrypt(&sender, &relay.public_key(), &[9; 32]).unwrap();
        for (events, disabled) in [
            (vec![], false),
            (vec!["push".to_string(), "pull_request".to_string()], true),
        ] {
            let input = NewWebhook {
                hook_id: hook_id_for_label("ci"),
                url: "https://hooks.example.com/dash".into(),
                events,
                relay_identity_id: ID.into(),
                secret: SecretBytes::new(vec![9; 32]),
                disabled,
                allow_credentials_in_url: false,
            };
            let p = webhook_props(
                REPO,
                [0x0d; 32],
                &input,
                (1, 2),
                ciphertext.clone(),
                Visibility::Public,
            );
            assert_valid("webhook", &p);
        }
        // `prepare` refuses a private repository first: the contract would too (publicOnly).
        let input = NewWebhook {
            hook_id: hook_id_for_label("ci"),
            url: "https://hooks.example.com/dash".into(),
            events: vec![],
            relay_identity_id: ID.into(),
            secret: SecretBytes::new(vec![9; 32]),
            disabled: false,
            allow_credentials_in_url: false,
        };
        let private = webhook_props(
            REPO,
            [0x0d; 32],
            &input,
            (1, 2),
            ciphertext,
            Visibility::Private,
        );
        assert_refused("webhook", &private, "publicOnly");
    }

    #[test]
    fn a_repo_key_wrap_is_rc1_valid() {
        use crate::envelope::PrivateKey;
        use crate::keyring::repo_key_fields;
        use crate::platform::wrap::{seal_wrap, test_contract, WrapParties, WrapSecret};
        let sender = WrapSecret::from_bytes(&SENDER_KEY).unwrap();
        let recipient = PrivateKey::from_slice(&RECIPIENT_KEY).unwrap().public_key();
        for epoch in [0, 3] {
            // Sealed as `post_wrap` seals it, through the SDK's encryptedFor helper.
            let sealed = seal_wrap(
                &test_contract(),
                &REPO,
                epoch,
                &EpochKey::from_bytes([5; 32]),
                &WrapParties {
                    sender: &sender,
                    sender_key_id: 2,
                    recipient_public_key: &recipient,
                    recipient_key_id: 1,
                },
            )
            .unwrap();
            let fields = repo_key_fields([0x33; 32], epoch, sealed);
            let doc = scoped(
                fields
                    .into_iter()
                    .map(|(k, v)| (k.to_string(), v))
                    .collect(),
            );
            assert_valid("repoKey", &doc);
        }
    }

    #[test]
    fn milestones_are_rc1_valid() {
        use crate::collab::parity::milestone_props;
        for (description, due_on, closed) in [
            ("", None, false),
            ("The review-parity release.", Some(1_764_547_200_000), true),
        ] {
            let p = milestone_props("v0.2", description, due_on, closed);
            public("milestone", p, By::Member);
        }
    }
}
