/**
 * Repo read services — the TS mirror of forge-core's RepoService read API.
 *
 * Composes the evo-sdk query layer + FORGE_RULES / FORGE_RULES_V2 into the reads a repo view
 * needs: resolve a repo (its forge-core `repo` document), enumerate + resolve refs, read
 * config / default branch, locate browse-plane pack manifests, fold issue/PR state, and read
 * the membership documents. Every query is scoped to the repo by a {@link RepoSource}.
 *
 * WRITE paths (repo creation and membership, issues, comments, events, author events,
 * reviews, releases, stars, follows) sign + broadcast via the `./writes` WriteEngine.
 */

export {
  DOC,
  asIdentifierString,
  byteFieldToHex,
  num,
  str,
  stringArray,
  repoContractIds,
  repoKey,
  toEvent,
  toRefUpdate,
  wellFormed,
  type RepoRef,
} from './contract'
export { CHUNK_QUERY_MAX, repoSource } from './source'
export {
  readRepoChrome,
  repoTimelines,
  chromeFallbacks,
  resetRepoTimelines,
  staleRepoTimelines,
  TIMELINE_TYPES,
  TIMELINES_FRESH_MS,
  type RepoChrome,
  type RepoTimelines,
  type TimelineType,
} from './chrome'
export {
  readRepoById,
  resolveAnyRepo,
  resolveAnyRepoWith,
  resolveOwner,
  toRepoDoc,
  repoRefOf,
  type RepoAddressParams,
  type ResolvedRepo,
  type RepoDoc,
} from './resolveRepo'
export {
  holdingsOfRole,
  invalidateMembers,
  membersGeneration,
  membershipsFromDocs,
  seedMemberships,
  readMemberRepoIds,
  readMemberships,
  readMembershipsCached,
  readProvenanceTrust,
  readRoleOracle,
  readViewerPermissions,
} from './members'
export {
  readFollowCounts,
  readFollowPage,
  type FollowPage,
  type FollowSide,
  readStarCount,
  readStargazers,
  readTargetCounts,
  readPublicRepoFacts,
} from './social'
export {
  compareRefNames,
  compareTagNames,
  isDraft,
  isPrerelease,
  isPrereleaseView,
  latestRelease,
  naturalRuns,
  newestPerTag,
  parseReleaseAssets,
  readReleases,
  releaseCountOf,
  releaseOrder,
  type ReleaseAssetView,
  type ReleaseList,
  type ReleaseView,
  type SealedReleaseInfo,
} from './releases'
export {
  readConfig,
  configBundleOf,
  readConfigBundle,
  readConfigHistory,
  readDefaultBranch,
  type ConfigBundle,
  type RepoConfig,
} from './config'
export {
  branchesOf,
  hasMissingParent,
  readAllRefUpdates,
  readRefUpdates,
  readRefs,
  refUpdatesFromRows,
  refsFromRows,
  resolveRefByHash,
  tagsOf,
  type ResolvedRef,
} from './refs'
export {
  readNewestFlatIndexManifest,
  readNewestLocatorManifest,
  readNewestManifestOfKind,
  readPackManifests,
  readRepoPackManifests,
  readBrowseManifests,
  readPackCopies,
  packsOfKind,
  type AsOf,
  type PackManifest,
} from './packs'
export {
  baseRefReaders,
  historicalTipsPredicate,
  readEvents,
  invalidateRepoFeed,
  groupFeed,
  issueViewOf,
  onRepoInvalidated,
  revisionOf,
  titleOf,
  toEvents,
  toLog,
  updatedAtOf,
  repoWriteGeneration,
  sharedRepoCounts,
  subscribeRepoLists,
  type TargetTotals,
  readTargetLog,
  readIssue,
  readPull,
  readReviews,
  reviewViewOf,
  verdictFromCode,
  VERDICT_LABEL,
  type IssueView,
  type PullView,
  type ReviewView,
  type TargetLog,
  type VerdictName,
} from './issues'
export {
  checkLabelInput,
  deleteLabel,
  defineLabel,
  labelTextColor,
  LABEL_COLORS,
  LABEL_LIMITS,
  newestLabels,
  planLabelDelete,
  readLabelDocs,
  readLabels,
  toLabelDef,
  type LabelDef,
} from './labels'
export {
  compareRows,
  matchesText,
  mentions,
  issueMilestoneItems,
  queryIssues,
  rowFiltersOf,
  rowMatches,
  type IssueListPage,
  type IssueRow,
  type IssueSelection,
  type RowFilters,
} from './issue-index'
export {
  pullMilestoneItems,
  pullsLinking,
  queryPulls,
  type LinkingPulls,
  type PullCounts,
  type PullListPage,
  type PullRow,
  type PullSelection,
  type PullStateFilter,
} from './pull-index'
export {
  acceptInvite,
  addEvent,
  beatAllowed,
  checkRepoInput,
  ConsentMissingError,
  createComment,
  createIssue,
  createPatch,
  patchData,
  createRelease,
  createRepo,
  createReview,
  discardRepoCreation,
  followRelation,
  findConsent,
  grantMember,
  LOCKED_REASON,
  lockedOut,
  nextNumber,
  normalizeRepoName,
  REPO_NAME_RULE,
  suggestRepoName,
  pendingRepoCreations,
  type ReleaseInput,
  readConsents,
  revokeMember,
  setLock,
  setTargetState,
  starRelation,
  watchRelation,
  DraftMarkError,
  type CreateRepoInput,
  type PrivateCreate,
  type CreateRepoStep,
  type PatchInput,
  type PostContext,
  type Relation,
  type RepoCreationJournal,
  type VerdictInput,
} from './writes'
export {
  IllegalTransitionError,
  readRepoCounts,
  readStateCodes,
  readTransitions,
  transitionOf,
  type StateTarget,
  type TransitionView,
} from './transitions'
export {
  commentFirsts,
  contractFirst,
  eventFirsts,
  followFirsts,
  issueFirsts,
  previewRepoCreate,
  repoCreationFirsts,
  reviewFirsts,
  starBeatFirsts,
  starFirsts,
  type RepoCreationFirsts,
} from './first-write'
export {
  EVENT_KIND_CODE,
  anchorData,
  commentData,
  deleteComment,
  discardReviewDraft,
  eventRoute,
  loadReviewDraft,
  postComment,
  postTargetEvent,
  recordPolicyBypass,
  reviewData,
  reviewDraftKey,
  saveReviewDraft,
  setAssignee,
  setLabel,
  setMilestone,
  setThreadFlag,
  setPolicy,
  submitReviewDraft,
  targetEventData,
  updateComment,
  updateTarget,
  type AnchorInput,
  type CommentInput,
  type DraftComment,
  type EventPayload,
  type ReviewDraft,
  type ReviewInput,
  type SubmitProgress,
  type SubmittedReview,
} from './review-writes'
export {
  manifestUrisProblem,
  onRepoContentWritten,
  refNameHash,
  repoContentWritten,
  refUpdateData,
  refUpdateType,
  writePackManifest,
  writeRefUpdate,
  type MovedRef,
  type PackManifestInput,
  type RefUpdateInput,
} from './push'
export {
  checkForkName,
  findForks,
  forkManifest,
  forkableRef,
  forkRepoV2,
  planFork,
  planManifests,
  planRefs,
  platformLocator,
  type ForkNameCheck,
  type ForkProgress,
  type ForkResult,
  type ForkStep,
} from './fork'
export { noteForkOf, readForkParent, resetForkParents } from './fork-parent'
export {
  DEFAULT_CONFIG,
  MAX_PROTECTED_PATTERNS,
  MERGE_METHODS,
  SealedConfigError,
  applyConfigChange,
  branchProblem,
  changeHolds,
  descriptionProblem,
  editRepoDoc,
  fullPattern,
  newestPolicy,
  policyFromDocs,
  parseTopics,
  patternMatches,
  patternsProblem,
  previewConfig,
  previewRepoEdit,
  readTopicDocNames,
  readPolicy,
  sameConfig,
  shortBranch,
  toPolicy,
  topicsProblem,
  updateConfig,
  type ConfigChange,
  type RepoDocEdit,
} from './settings'
