/**
 * Repo read services — the TS mirror of forge-core's RepoService read API.
 *
 * Composes the evo-sdk query layer + FORGE_RULES / FORGE_RULES_V2 into the reads a repo view
 * needs: resolve a repo (its forge-core `repo` document), enumerate + resolve refs, read
 * config / default branch, locate browse-plane pack manifests, fold issue/PR state, and read
 * the membership documents. Every query is scoped to the repo by a {@link RepoSource}.
 *
 * WRITE paths (repo creation and membership, issues, comments, events, author events,
 * reviews, releases, stars, follows) sign + broadcast via the `./writes` WriteEngine.
 */

export {
  DOC,
  asIdentifierString,
  byteFieldToHex,
  num,
  str,
  stringArray,
  repoContractIds,
  repoKey,
  toEvent,
  toRefUpdate,
  wellFormed,
  type RepoRef,
} from './contract'
export { CHUNK_QUERY_MAX, repoSource } from './source'
export {
  readRepoById,
  resolveAnyRepo,
  resolveAnyRepoWith,
  resolveOwner,
  toRepoDoc,
  repoRefOf,
  type RepoAddressParams,
  type ResolvedRepo,
  type RepoDoc,
} from './resolveRepo'
export {
  holdingsOfRole,
  invalidateMembers,
  membershipsFromDocs,
  seedMemberships,
  readMemberRepoIds,
  readMemberships,
  readMembershipsCached,
  readRoleOracle,
  readViewerPermissions,
} from './members'
export {
  readFollowCounts,
  readStarCount,
  readStargazers,
  readTargetCounts,
  readPublicRepoFacts,
} from './social'
export {
  isPrerelease,
  latestRelease,
  newestPerTag,
  parseReleaseAssets,
  readReleases,
  releaseOrder,
  type ReleaseAssetView,
  type ReleaseList,
  type ReleaseView,
} from './releases'
export {
  readConfig,
  readConfigBundle,
  readConfigHistory,
  readDefaultBranch,
  type ConfigBundle,
  type RepoConfig,
} from './config'
export {
  branchesOf,
  hasMissingParent,
  readAllRefUpdates,
  readRefUpdates,
  readRefs,
  resolveRefByHash,
  tagsOf,
  type ResolvedRef,
} from './refs'
export {
  readNewestFlatIndexManifest,
  readNewestLocatorManifest,
  readNewestManifestOfKind,
  readPackManifests,
  readRepoPackManifests,
  readPackCopies,
  packsOfKind,
  type AsOf,
  type PackManifest,
} from './packs'
export {
  foldOpenCounts,
  foldsForCount,
  historicalTipsPredicate,
  LIST_PAGE,
  listIssues,
  listIssuesCached,
  listPulls,
  listPullsCached,
  openCountFor,
  openCountOf,
  openCounts,
  readEvents,
  invalidateRepoFeed,
  groupFeed,
  issueViewOf,
  onRepoInvalidated,
  revisionOf,
  seedRepoFeed,
  settleIssueCount,
  titleOf,
  toEvents,
  toLog,
  updatedAtOf,
  repoListVersion,
  repoWriteGeneration,
  subscribeRepoLists,
  type TargetTotals,
  readTargetLog,
  readIssue,
  readPull,
  readReviews,
  reviewViewOf,
  verdictFromCode,
  VERDICT_LABEL,
  type IssueView,
  type Listed,
  type PullView,
  type ReviewView,
  type TargetLog,
  type VerdictName,
} from './issues'
export {
  checkLabelInput,
  defineLabel,
  labelTextColor,
  LABEL_COLORS,
  LABEL_LIMITS,
  newestLabels,
  readLabels,
  toLabelDef,
  type LabelDef,
} from './labels'
export {
  compareRows,
  foldIssueOpenCount,
  matchesText,
  mentions,
  queryIssues,
  rowMatches,
  type IssueListPage,
  type IssueRow,
  type IssueSelection,
} from './issue-index'
export {
  addAuthorEvent,
  addEvent,
  checkRepoInput,
  createComment,
  createIssue,
  createPatch,
  patchData,
  createRelease,
  createRepo,
  createReview,
  discardRepoCreation,
  followRelation,
  grantMember,
  nextNumber,
  normalizeRepoName,
  pendingRepoCreations,
  revokeMember,
  setTargetState,
  starRelation,
  stateEventRoute,
  type CreateRepoInput,
  type PrivateCreate,
  type CreateRepoStep,
  type PatchInput,
  type Relation,
  type RepoCreationJournal,
  type VerdictInput,
} from './writes'
export {
  commentFirsts,
  contractFirst,
  eventFirsts,
  followFirsts,
  issueFirsts,
  repoCreationFirsts,
  reviewFirsts,
  starFirsts,
} from './first-write'
export {
  EVENT_KIND_CODE,
  anchorData,
  commentData,
  discardReviewDraft,
  eventRoute,
  loadReviewDraft,
  postComment,
  postTargetEvent,
  reviewData,
  reviewDraftKey,
  saveReviewDraft,
  setAssignee,
  setLabel,
  setPolicy,
  submitReviewDraft,
  targetEventData,
  updateComment,
  updateTarget,
  type AnchorInput,
  type CommentInput,
  type DraftComment,
  type EventPayload,
  type ReviewDraft,
  type ReviewInput,
  type SubmitProgress,
  type SubmittedReview,
} from './review-writes'
export {
  manifestUrisProblem,
  onRepoContentWritten,
  refNameHash,
  repoContentWritten,
  refUpdateData,
  refUpdateType,
  writePackManifest,
  writeRefUpdate,
  type MovedRef,
  type PackManifestInput,
  type RefUpdateInput,
} from './push'
export {
  checkForkName,
  findForks,
  forkManifest,
  forkRepoV2,
  planFork,
  planManifests,
  planRefs,
  platformLocator,
  type ForkNameCheck,
  type ForkProgress,
  type ForkResult,
  type ForkStep,
} from './fork'
export {
  DEFAULT_CONFIG,
  MAX_PROTECTED_PATTERNS,
  MERGE_METHODS,
  SealedConfigError,
  applyConfigChange,
  branchProblem,
  changeHolds,
  descriptionProblem,
  editRepoDoc,
  fullPattern,
  newestPolicy,
  parseTopics,
  patternMatches,
  patternsProblem,
  previewConfig,
  previewRepoEdit,
  readPolicy,
  sameConfig,
  shortBranch,
  toPolicy,
  topicsProblem,
  updateConfig,
  type ConfigChange,
  type RepoDocEdit,
} from './settings'
