// copy-lint-ignore-file: test and script helper; app code never imports it.
/**
 * An offline judge of forge-v2 RC1 documents: does a node accept this document create?
 *
 * It judges a document the way the RC1 vectors (`forge-contracts/vectors/rc1`, generated by
 * `forge-contracts/schema/vectors.py`) and their reference judge (`tools/contract-validate`,
 * rs-dpp 5.0.0-beta.1 `validate_document_properties`) do: the JSON schema, then `maxBytes`, then every
 * `propertyConstraints` rule that reads no `countOf`/`sumOf` total and no block height. Like
 * the node it reports the first stage that fails and nothing after it, so a schema error keeps
 * precedence over a byte cap or a rule.
 *
 * The schema check is a small interpreter of the subset the RC1 contracts use (see
 * {@link checkSchema}); the rules are judged by the pinned wasm SDK
 * (`DataContract.checkDocumentPropertyConstraints`), the same code consensus runs.
 *
 * FOR TESTS AND SCRIPTS ONLY: it reads the contracts with `node:fs`, so app code must never
 * import it (the app writes through `lib/sdk/write.ts`, where the node is the judge).
 *
 * Documents are given as a writer builds them: identifiers and byte arrays as `Uint8Array`
 * (`decodeIdentifier` for identifiers), integers as `number`, and no system (`$`-prefixed)
 * fields. A `bigint` is refused as a `type` error: the wasm `Document` does not carry one as an
 * integer (every rule reading it fails `NotAnInteger`), so a writer must not send one.
 */

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { base58Decode, base58Encode } from '../auth/base58'
import { contractKindOfType } from '../layout'

type Evo = typeof import('@dashevo/evo-sdk')
type Json = Record<string, unknown>
type Schema = Record<string, unknown>

/** The three RC1 contracts, by file name. */
/** The consensus code a `maxBytes` refusal carries (`DocumentFieldMaxSizeExceededError`); a vector's `why` may name it. */
const MAX_BYTES_CODE = 10417

export type Rc1ContractName = 'forge-core' | 'forge-collab' | 'forge-community'
const NAMES: readonly Rc1ContractName[] = ['forge-core', 'forge-collab', 'forge-community']

/**
 * The ids the contracts' cross-contract placeholders stand for (`IDS` in vectors.py), and one
 * for forge-community (which nothing references). Any valid ids do: nothing is fetched.
 */
const CONTRACT_IDS: Readonly<Record<Rc1ContractName, string>> = {
  'forge-core': 'A2KL77ngVM1ft1t1em2XKt1rWCBZANdAJMyfWrDGCcd1',
  'forge-collab': 'C1zHeeG7EUudXdB5ZyDQnXVU35hrCfvd1fRCybXEqaPS',
  'forge-community': 'HwhCv9N5BHsbGNLzDR4tnZnqJ6VxtwJSLsM4aUWn2Tnr',
}

/** The signer of every vector case (0x07 × 32), the default owner of a judged document. */
export const RC1_VECTOR_OWNER = base58Encode(new Uint8Array(32).fill(7))

/** The protocol version the reference judge uses (rs-dpp `PlatformVersion::get(14)`). */
const PLATFORM_VERSION = 14

let contractsCache: Record<Rc1ContractName, Json> | undefined

/**
 * The frozen RC1 contract JSONs (`forge-contracts/contracts`), with the cross-contract
 * placeholders replaced by {@link CONTRACT_IDS} and `id` / `ownerId` set, ready for
 * `DataContract.fromJSON`. Read once and cached; treat the result as read-only.
 */
export function rc1Contracts(): Record<Rc1ContractName, Json> {
  if (contractsCache) return contractsCache
  const dir = resolve(__dirname, '..', '..', '..', 'forge-contracts', 'contracts')
  const read = (name: Rc1ContractName): Json => {
    const text = readFileSync(resolve(dir, `${name}.json`), 'utf8')
      .replaceAll('FORGE_CORE_CONTRACT_ID', CONTRACT_IDS['forge-core'])
      .replaceAll('FORGE_COLLAB_CONTRACT_ID', CONTRACT_IDS['forge-collab'])
    return { ...(JSON.parse(text) as Json), id: CONTRACT_IDS[name], ownerId: RC1_VECTOR_OWNER }
  }
  contractsCache = Object.fromEntries(NAMES.map((n) => [n, read(n)])) as Record<Rc1ContractName, Json>
  return contractsCache
}

/** The RC1 contract holding `type` (the layout's map). Throws on a type no contract holds. */
export function rc1ContractOf(type: string): Rc1ContractName {
  const kind = contractKindOfType(type)
  if (kind === null) throw new Error(`no forge-v2 contract holds the document type ${JSON.stringify(type)}`)
  return `forge-${kind}` as Rc1ContractName
}

// ---------------------------------------------------------------------------------------------
// JSON schema (the subset the RC1 contracts use)
// ---------------------------------------------------------------------------------------------

/** Unicode `White_Space`, what Rust `regex` means by `\s` (JS `\s` differs at U+0085 and U+FEFF). */
const RUST_SPACE = '\\t\\n\\v\\f\\r \\x85\\xa0\\u1680\\u2000-\\u200a\\u2028\\u2029\\u202f\\u205f\\u3000'

/** The ASCII POSIX classes Rust `regex` accepts inside brackets (`[[:space:]]`). */
const POSIX: Readonly<Record<string, string>> = {
  alnum: '0-9A-Za-z',
  alpha: 'A-Za-z',
  blank: '\\t ',
  cntrl: '\\x00-\\x1f\\x7f',
  digit: '0-9',
  lower: 'a-z',
  space: '\\t\\n\\v\\f\\r ',
  upper: 'A-Z',
  word: '0-9A-Za-z_',
  xdigit: '0-9A-Fa-f',
}

const patternCache = new Map<string, RegExp>()

/**
 * A contract `pattern` (Rust `regex` syntax, unanchored unless it anchors itself) as a JS
 * `RegExp` with the `u` flag. Translates what JS lacks or reads differently: POSIX classes,
 * `\s` / `\S` (Unicode `White_Space`) and `\d` / `\D` (Unicode digits). Throws on a construct
 * whose meaning differs and that no RC1 contract uses (`\w`, `\b`, `\x{..}`, a negated POSIX
 * class, `\S` inside brackets), so a contract change cannot silently widen or narrow a check.
 */
function rustPattern(rust: string): RegExp {
  const cached = patternCache.get(rust)
  if (cached) return cached
  let out = ''
  let inClass = false
  for (let i = 0; i < rust.length; i++) {
    const c = rust[i] as string
    if (c === '\\') {
      const e = rust[++i] ?? ''
      if (e === 's') out += inClass ? RUST_SPACE : `[${RUST_SPACE}]`
      else if (e === 'S' && !inClass) out += `[^${RUST_SPACE}]`
      else if (e === 'd') out += '\\p{Nd}'
      else if (e === 'D') out += '\\P{Nd}'
      else if ('SwWbB'.includes(e) || (e === 'x' && rust[i + 1] === '{'))
        throw new Error(`rc1-validate: pattern ${JSON.stringify(rust)} uses \\${e}, which this translator does not support`)
      else out += `\\${e}`
    } else if (inClass && c === '[' && rust[i + 1] === ':') {
      const end = rust.indexOf(':]', i)
      const set = POSIX[rust.slice(i + 2, end)]
      if (end < 0 || set === undefined) throw new Error(`rc1-validate: unsupported POSIX class in ${JSON.stringify(rust)}`)
      out += set
      i = end + 1
    } else if (!inClass && c === '[') {
      inClass = true
      out += c
      if (rust[i + 1] === '^') out += rust[++i]
      if (rust[i + 1] === ']') out += `\\${rust[++i]}` // a leading `]` is a literal in Rust
    } else {
      if (c === ']') inClass = false
      out += c
    }
  }
  const re = new RegExp(out, 'u')
  patternCache.set(rust, re)
  return re
}

/** A value's identity for `enum`, `const` and `uniqueItems` (bytes compare as arrays). */
function canonical(value: unknown): string {
  return JSON.stringify(value, (_k, v: unknown) => (v instanceof Uint8Array ? Array.from(v) : typeof v === 'bigint' ? `${v}n` : v))
}

function isPlainObject(value: unknown): value is Json {
  return typeof value === 'object' && value !== null && !Array.isArray(value) && !(value instanceof Uint8Array)
}

function typeOk(type: unknown, value: unknown, byteArray: boolean): boolean {
  switch (type) {
    case 'array':
      return byteArray ? value instanceof Uint8Array : Array.isArray(value)
    case 'object':
      return isPlainObject(value)
    case 'string':
      return typeof value === 'string'
    case 'integer':
      return Number.isInteger(value)
    case 'number':
      return typeof value === 'number' && Number.isFinite(value)
    case 'boolean':
      return typeof value === 'boolean'
    default:
      throw new Error(`rc1-validate: unsupported schema type ${JSON.stringify(type)}`)
  }
}

interface SchemaRun {
  readonly defs: Readonly<Record<string, Schema>>
  /** JSON-schema failures: each `<keyword> at <path>`. */
  readonly errors: string[]
  /** `maxBytes` failures, reported only when the schema passes (as the node does). */
  readonly bytes: string[]
}

/**
 * Checks `value` at `path` against `schema`: `$ref` to `#/$defs/*`, `type` (a `byteArray`
 * array is a `Uint8Array`, its items the bytes), `enum`, `const`, `minimum` / `maximum`,
 * `minLength` / `maxLength` (Unicode scalar values, as Rust's `chars().count()`), `pattern`,
 * `maxBytes` (UTF-8 bytes), `minItems` / `maxItems`, `uniqueItems`, `items`, and objects'
 * `properties` / `required` (system `$` fields skipped) / `additionalProperties: false` /
 * `dependentRequired`. Annotations (`position`, `contentMediaType`, `refersTo`, `encryptedFor`,
 * `indices`, `immutable`, ...) judge nothing and are ignored.
 */
function checkSchema(schema: Schema, value: unknown, path: string, run: SchemaRun): void {
  const at = path || '/'
  const fail = (keyword: string, detail: string) => run.errors.push(`${keyword} at ${at}: ${detail}`)
  const ref = schema.$ref
  if (typeof ref === 'string') {
    const def = ref.startsWith('#/$defs/') ? run.defs[ref.slice('#/$defs/'.length)] : undefined
    if (!def) throw new Error(`rc1-validate: unresolvable $ref ${ref}`)
    checkSchema(def, value, path, run)
  }
  if (schema.type !== undefined && !typeOk(schema.type, value, schema.byteArray === true)) {
    fail('type', `expected ${schema.byteArray ? 'a byte array (Uint8Array)' : String(schema.type)}`)
    return
  }
  if (Array.isArray(schema.enum) && !schema.enum.some((e) => canonical(e) === canonical(value)))
    fail('enum', `${canonical(value)} is not one of ${canonical(schema.enum)}`)
  if ('const' in schema && canonical(schema.const) !== canonical(value)) fail('const', `${canonical(value)} is not ${canonical(schema.const)}`)

  if (typeof value === 'number') {
    if (typeof schema.minimum === 'number' && value < schema.minimum) fail('minimum', `${value} < ${schema.minimum}`)
    if (typeof schema.maximum === 'number' && value > schema.maximum) fail('maximum', `${value} > ${schema.maximum}`)
  } else if (typeof value === 'string') {
    const chars = [...value].length
    if (typeof schema.minLength === 'number' && chars < schema.minLength) fail('minLength', `${chars} chars < ${schema.minLength}`)
    if (typeof schema.maxLength === 'number' && chars > schema.maxLength) fail('maxLength', `${chars} chars > ${schema.maxLength}`)
    if (typeof schema.pattern === 'string' && !rustPattern(schema.pattern).test(value))
      fail('pattern', `${JSON.stringify(value.slice(0, 60))} does not match ${schema.pattern}`)
    const bytes = new TextEncoder().encode(value).length
    if (typeof schema.maxBytes === 'number' && bytes > schema.maxBytes) run.bytes.push(`maxBytes at ${at}: ${bytes} B > ${schema.maxBytes} (${MAX_BYTES_CODE})`)
  } else if (value instanceof Uint8Array || Array.isArray(value)) {
    const n = value.length
    if (typeof schema.minItems === 'number' && n < schema.minItems) fail('minItems', `${n} items < ${schema.minItems}`)
    if (typeof schema.maxItems === 'number' && n > schema.maxItems) fail('maxItems', `${n} items > ${schema.maxItems}`)
    if (Array.isArray(value)) {
      if (schema.uniqueItems === true && new Set(value.map(canonical)).size !== n) fail('uniqueItems', 'items repeat')
      if (isPlainObject(schema.items)) value.forEach((item, i) => checkSchema(schema.items as Schema, item, `${path}/${i}`, run))
    }
  } else if (isPlainObject(value)) {
    checkObject(schema, value, path, run, fail)
  }
}

function checkObject(schema: Schema, value: Json, path: string, run: SchemaRun, fail: (keyword: string, detail: string) => void): void {
  const properties = (schema.properties ?? {}) as Record<string, Schema>
  for (const name of (schema.required ?? []) as string[]) {
    if (!name.startsWith('$') && value[name] === undefined) fail('required', `${JSON.stringify(name)} is missing`)
  }
  for (const [trigger, needs] of Object.entries((schema.dependentRequired ?? {}) as Record<string, string[]>)) {
    if (value[trigger] === undefined) continue
    for (const name of needs) {
      if (value[name] === undefined) fail('required', `${JSON.stringify(name)} is missing (dependentRequired by ${JSON.stringify(trigger)})`)
    }
  }
  for (const [name, v] of Object.entries(value)) {
    if (v === undefined) continue
    const sub = properties[name]
    if (sub) checkSchema(sub, v, `${path}/${name}`, run)
    else if (schema.additionalProperties === false) fail('additionalProperties', `${JSON.stringify(name)} is not a property`)
  }
}

// ---------------------------------------------------------------------------------------------
// propertyConstraints (the pinned wasm SDK)
// ---------------------------------------------------------------------------------------------

interface Judge {
  readonly evo: Evo
  readonly contracts: Readonly<Record<Rc1ContractName, InstanceType<Evo['DataContract']>>>
}

let judgePromise: Promise<Judge> | undefined

/** The wasm SDK and the three parsed contracts, loaded once. */
function judge(): Promise<Judge> {
  judgePromise ??= (async () => {
    const evo = await import('@dashevo/evo-sdk')
    await evo.EvoSDK.getLatestVersionNumber() // loads the wasm module
    const json = rc1Contracts()
    const parse = (name: Rc1ContractName) =>
      evo.DataContract.fromJSON(json[name] as Parameters<Evo['DataContract']['fromJSON']>[0], true, PLATFORM_VERSION)
    return { evo, contracts: Object.fromEntries(NAMES.map((n) => [n, parse(n)])) as Judge['contracts'] }
  })()
  return judgePromise
}

// ---------------------------------------------------------------------------------------------
// API
// ---------------------------------------------------------------------------------------------

export type Rc1Verdict = { ok: true } | { ok: false; errors: string[] }

/**
 * Judges `doc` as a create of document type `type` by `opts.owner` (base58; default
 * {@link RC1_VECTOR_OWNER}): the JSON schema first (every failure, each naming its keyword and
 * path, e.g. `pattern at /refName: ...`), else `maxBytes`, else the first broken
 * `propertyConstraints` rule (`propertyConstraints <rule> (<violation>): ...`). Rules reading a
 * total or a block height are not judged (the live suite covers them); rules reading
 * `$createdAt` / `$updatedAt` use the device clock, as the wasm pre-check does.
 */
export async function validateRc1(type: string, doc: Record<string, unknown>, opts?: { owner?: string }): Promise<Rc1Verdict> {
  const name = rc1ContractOf(type)
  const contract = rc1Contracts()[name]
  const documentSchemas = contract.documentSchemas as Record<string, Schema>
  const schema = documentSchemas[type]
  if (!schema) throw new Error(`rc1-validate: ${name} has no document type ${JSON.stringify(type)}`)
  const run: SchemaRun = { defs: (contract.schemaDefs ?? {}) as Record<string, Schema>, errors: [], bytes: [] }
  checkSchema(schema, doc, '', run)
  if (run.errors.length > 0) return { ok: false, errors: run.errors }
  if (run.bytes.length > 0) return { ok: false, errors: run.bytes }
  const shape = structureErrors(schema, doc, opts?.owner ?? RC1_VECTOR_OWNER)
  if (shape.length > 0) return { ok: false, errors: shape }

  const { evo, contracts } = await judge()
  const document = new evo.Document({
    documentTypeName: type,
    dataContractId: CONTRACT_IDS[name],
    ownerId: opts?.owner ?? RC1_VECTOR_OWNER,
    properties: doc,
  })
  const broken = contracts[name].checkDocumentPropertyConstraints(document)
  return broken ? { ok: false, errors: [`propertyConstraints ${broken.rule} (${broken.violation}): ${broken.message}`] } : { ok: true }
}

/**
 * The checks a node runs on a create right after the schema (drive-abci's advanced structure,
 * as `tools/contract-validate` judges the vectors): a `distinctFrom` property differs from the
 * writer or its sibling (10419), and an `encryptedFor` ciphertext is at least 32 bytes and a
 * whole number of 16-byte AES blocks (10420).
 */
function structureErrors(schema: Schema, doc: Record<string, unknown>, owner: string): string[] {
  const errors: string[] = []
  const props = (schema.properties ?? {}) as Record<string, Schema & { distinctFrom?: string; encryptedFor?: unknown }>
  for (const [name, prop] of Object.entries(props)) {
    const value = doc[name]
    if (value === undefined) continue
    if (typeof prop.distinctFrom === 'string') {
      const other = prop.distinctFrom === '$ownerId' ? base58Decode(owner) : doc[prop.distinctFrom]
      if (value instanceof Uint8Array && sameValue(value, other)) errors.push(`distinctFrom at /${name}: equals ${prop.distinctFrom} (${DISTINCT_FROM_CODE})`)
    }
    if (prop.encryptedFor !== undefined && value instanceof Uint8Array && (value.length < 32 || value.length % 16 !== 0)) {
      errors.push(`encryptedFor at /${name}: ${value.length} bytes is no AES-CBC ciphertext (${ENCRYPTED_SHAPE_CODE})`)
    }
  }
  return errors
}

/** The consensus codes of the two structure checks (`distinctFrom`, the `encryptedFor` shape). */
const DISTINCT_FROM_CODE = 10419
const ENCRYPTED_SHAPE_CODE = 10420

/**
 * Throws, listing every error, unless {@link validateRc1} accepts `doc` as a create of `type`
 * by `owner` (base58; default {@link RC1_VECTOR_OWNER}). For tests that check what a writer
 * builds: pass the document as the writer hands it to the SDK (identifiers and bytes as
 * `Uint8Array`).
 */
export async function expectRc1Valid(type: string, doc: Record<string, unknown>, owner?: string): Promise<void> {
  const verdict = await validateRc1(type, doc, { owner })
  if (!verdict.ok) throw new Error(`RC1 refuses this ${type} document:\n  ${verdict.errors.join('\n  ')}`)
}

// ---------------------------------------------------------------------------------------------
// Replaces (v5 `immutable`, with conditions) and index shapes (RC2)
// ---------------------------------------------------------------------------------------------

/** Byte-aware deep equality of two document values (`Uint8Array`s by content). */
function sameValue(a: unknown, b: unknown): boolean {
  if (a instanceof Uint8Array || b instanceof Uint8Array) {
    return a instanceof Uint8Array && b instanceof Uint8Array && a.length === b.length && a.every((x, i) => x === b[i])
  }
  if (Array.isArray(a) || Array.isArray(b)) {
    return Array.isArray(a) && Array.isArray(b) && a.length === b.length && a.every((x, i) => sameValue(x, b[i]))
  }
  if (a !== null && b !== null && typeof a === 'object' && typeof b === 'object') {
    const ka = Object.keys(a as Json)
    const kb = Object.keys(b as Json)
    return ka.length === kb.length && ka.every((k) => k in (b as Json) && sameValue((a as Json)[k], (b as Json)[k]))
  }
  return a === b
}

/**
 * A `when` condition of an `immutable` entry, judged on the replace (`doc`) with the stored
 * document under `$old.`. The subset the forge contracts use: `present`, `equal` (operands a
 * path or `{ const }`), `not`, `all`, `any`. Anything else throws, so a new form is never
 * silently judged as "not holding".
 */
function conditionHolds(cond: unknown, doc: Json, stored: Json): boolean {
  const read = (path: string): unknown => {
    const [from, rest] = path.startsWith('$old.') ? [stored, path.slice(5)] : [doc, path]
    // A system field ($updatedAt is the replace's block time, $ownerId, ...) is not in the
    // properties this judge holds: refuse to guess rather than read it as absent.
    if (rest.startsWith('$')) throw new Error(`rc1-validate: an immutable condition reads ${path}, which this judge does not hold`)
    return rest.split('.').reduce<unknown>((o, k) => (o !== null && typeof o === 'object' ? (o as Json)[k] : undefined), from)
  }
  const operand = (o: unknown): unknown => (typeof o === 'string' ? read(o) : o !== null && typeof o === 'object' && 'const' in o ? (o as Json).const : o)
  const c = cond as Json
  if (typeof c.present === 'string') return read(c.present) !== undefined
  if (Array.isArray(c.equal) && c.equal.length === 2) return sameValue(operand(c.equal[0]), operand(c.equal[1]))
  if ('not' in c) return !conditionHolds(c.not, doc, stored)
  if (Array.isArray(c.all)) return c.all.every((x) => conditionHolds(x, doc, stored))
  if (Array.isArray(c.any)) return c.any.some((x) => conditionHolds(x, doc, stored))
  throw new Error(`rc1-validate: an immutable condition this judge does not read: ${JSON.stringify(cond)}`)
}

/**
 * Judges `doc` as a replace of `stored` (both the document's properties), in the order a v5 node
 * does (`forge-contracts/vectors/rc1/README.md`, "Replace vectors"): the properties as for a
 * create ({@link validateRc1}), then `immutable`. Every top-level property that differs (changed,
 * added or removed) is refused with `40128` when the type lists it by name, or with a condition
 * that holds. The entries come from the pinned SDK's parse of the contract
 * (`documentTypeImmutableProperties`: `immutable` and `immutableWhen`), so this also checks the
 * SDK reads the conditions the contract declares.
 */
export async function validateRc1Replace(type: string, stored: Json, doc: Json, opts?: { owner?: string }): Promise<Rc1Verdict> {
  const asCreate = await validateRc1(type, doc, opts)
  if (!asCreate.ok) return asCreate
  const { contracts } = await judge()
  const { immutable, immutableWhen } = contracts[rc1ContractOf(type)].documentTypeImmutableProperties(type)
  const fixed = new Set(immutable)
  const changed = [...new Set([...Object.keys(stored), ...Object.keys(doc)])].filter((k) => !sameValue(stored[k], doc[k])).sort()
  for (const key of changed) {
    const when = (immutableWhen as Record<string, unknown>)[key]
    if (fixed.has(key) || (when !== undefined && conditionHolds(when, doc, stored))) {
      return { ok: false, errors: [`immutable at /${key}: changed by a replace (40128)`] }
    }
  }
  return { ok: true }
}

/** One index of a document type, as Drive lays it out for the pinned SDK's parse of the contract. */
export interface Rc1IndexFacts {
  /** The index's properties in order (a time window's property without its `#range#step`). */
  readonly properties: readonly string[]
  readonly flags: Readonly<Record<'unique' | 'rangeCountable' | 'rankedCountable' | 'outlivesDelete' | 'timeRange' | 'derived', boolean>>
}

/** A node of `documentTypeLayout` (wasm-sdk 5.0.0-beta.1 `DocumentTypeLayoutNode`), as far as this reads it. */
interface LayoutNode {
  readonly key: { readonly kind: string; readonly label?: string }
  readonly role: string
  readonly element: string
  readonly rankedAxes: readonly string[]
  readonly indexes: readonly string[]
  readonly notes: readonly { readonly code: string }[]
  readonly alternative?: { readonly node: LayoutNode }
  readonly children: readonly LayoutNode[]
}

/**
 * Whether `contract` has document type `type`, and its indexes by name, read from Drive's layout
 * of the pinned SDK's (fully validated) parse (`documentTypeLayout`), for the RC2 index vectors
 * (`<contract>.indices.json`). Below the type's root, every tree of an index names it: its
 * property trees give the order, a `timeRangeBucket` layer the time window, a `count` ranking
 * axis `rankedCountable`, a provable count tree `rangeCountable`, and an `outlivesDelete` note
 * the delete rule. `unique` (not visible in the layout) comes from the parsed schema; `derived`
 * is a property read through a reference (`patchId.$ownerId`).
 */
export async function rc1Indexes(contract: Rc1ContractName, type: string): Promise<ReadonlyMap<string, Rc1IndexFacts> | null> {
  const { evo, contracts } = await judge()
  const parsed = contracts[contract]
  const schema = (parsed.schemas as Record<string, { indices?: Json[] }>)[type]
  if (!schema) return null
  const nodes = new Map<string, LayoutNode[]>()
  const walk = (node: LayoutNode): void => {
    if (node.role !== 'documentType') for (const name of node.indexes) nodes.set(name, [...(nodes.get(name) ?? []), node])
    for (const child of node.children) walk(child)
    if (node.alternative) walk(node.alternative.node)
  }
  walk(evo.documentTypeLayout(parsed, type, PLATFORM_VERSION).root as unknown as LayoutNode)
  const out = new Map<string, Rc1IndexFacts>()
  for (const index of schema.indices ?? []) {
    const name = index.name as string
    const path = nodes.get(name) ?? []
    if (path.length === 0) continue // not laid out: absent as far as Drive is concerned
    const properties = path.filter((n) => n.role === 'indexProperty' || n.role === 'nextIndexProperty').map((n) => (n.key.label ?? '').split('#')[0] as string)
    out.set(name, {
      properties,
      flags: {
        unique: index.unique === true,
        rangeCountable: path.some((n) => n.element.startsWith('ProvableCount')),
        rankedCountable: path.some((n) => n.rankedAxes.includes('count')),
        outlivesDelete: path.some((n) => n.notes.some((note) => note.code === 'outlivesDelete')),
        timeRange: path.some((n) => n.key.kind === 'timeRangeBucket'),
        derived: properties.some((p) => p.includes('.')),
      },
    })
  }
  return out
}
