/**
 * The RC1 conformance vectors (`forge-contracts/vectors/rc1/<contract>.json`, generated by
 * `forge-contracts/schema/vectors.py` and judged there by b7gate, rs-dpp 4.2.0-beta.7) through
 * the offline judge in `rc1-validate.ts`: every `ok` case must be accepted, every `refused` case
 * refused with an error naming the case's `why` (a schema keyword or a `propertyConstraints`
 * rule). So forge-web and the reference judge agree on what RC1 accepts, and the judge the
 * writer tests use (`expectRc1Valid`) is itself checked against the reference.
 *
 * In a case's `doc` (`forge-contracts/vectors/rc1/README.md`), `{"$id": n}` is the identifier of
 * 32 bytes of `n` or `{"$id": "<base58>"}` that id, `{"$b": [fill, len]}` is `len` bytes of `fill`
 * and `{"$hex": "…"}` those bytes; all become `Uint8Array`s, as writers pass them. A case's
 * `owner` (a byte `n` or a base58 id) is its signer, `0x07 × 32` when absent.
 */

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { beforeAll, describe, expect, it } from 'vitest'
import { hexToBytes } from '@noble/hashes/utils.js'
import { base58Decode, base58Encode } from '../auth/base58'
import { rc1ContractOf, rc1Contracts, validateRc1, type Rc1ContractName } from './rc1-validate'

interface VectorCase {
  item: string
  name: string
  type: string
  expect: 'ok' | 'refused'
  why?: string
  owner?: number | string
  doc: Record<string, unknown>
}

const CONTRACTS: readonly Rc1ContractName[] = ['forge-core', 'forge-collab', 'forge-community']
/** The number of cases vectors.py writes; a dropped or truncated file changes it. */
const TOTAL_CASES = 376

/** A case's signer as base58: a byte `n` is 32 bytes of `n`; absent is the vectors' default. */
function ownerOf(owner: number | string | undefined): string | undefined {
  if (owner === undefined) return undefined
  return typeof owner === 'string' ? owner : base58Encode(new Uint8Array(32).fill(owner))
}

/** A vector value with its `$id` / `$b` / `$hex` placeholders as bytes. */
function materialise(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(materialise)
  if (value === null || typeof value !== 'object') return value
  const o = value as Record<string, unknown>
  if ('$id' in o) return typeof o.$id === 'string' ? base58Decode(o.$id) : new Uint8Array(32).fill(o.$id as number)
  if ('$hex' in o) return hexToBytes(o.$hex as string)
  if ('$b' in o) {
    const [fill, len] = o.$b as [number, number]
    return new Uint8Array(len).fill(fill)
  }
  return Object.fromEntries(Object.entries(o).map(([k, v]) => [k, materialise(v)]))
}

const vectors: Record<Rc1ContractName, VectorCase[]> = Object.fromEntries(
  CONTRACTS.map((name) => {
    const path = resolve(__dirname, '..', '..', '..', 'forge-contracts', 'vectors', 'rc1', `${name}.json`)
    return [name, JSON.parse(readFileSync(path, 'utf8')) as VectorCase[]]
  }),
) as Record<Rc1ContractName, VectorCase[]>

describe('RC1 conformance vectors', () => {
  beforeAll(async () => {
    // Loads the wasm SDK and parses the contracts once, outside any one case's timeout.
    await validateRc1('star', { repoId: new Uint8Array(32).fill(1) })
  }, 60_000)

  it(`has all ${TOTAL_CASES} cases`, () => {
    expect(CONTRACTS.reduce((n, c) => n + vectors[c].length, 0)).toBe(TOTAL_CASES)
  })

  it.each(CONTRACTS)('%s: every document type has an ok base case, and each case sits in its type’s contract', (name) => {
    const types = Object.keys(rc1Contracts()[name].documentSchemas as object)
    const baseOk = new Set(vectors[name].filter((c) => c.item === 'base' && c.expect === 'ok').map((c) => c.type))
    expect(types.filter((t) => !baseOk.has(t))).toEqual([])
    for (const t of types) expect(rc1ContractOf(t)).toBe(name)
    for (const c of vectors[name]) expect(rc1ContractOf(c.type)).toBe(name)
  })

  for (const name of CONTRACTS) {
    describe(name, () => {
      it.each(vectors[name].map((c) => [`${c.item} ${c.type}: ${c.name}`, c] as const))('%s', async (_label, c) => {
        const owner = ownerOf(c.owner)
        const verdict = await validateRc1(c.type, materialise(c.doc) as Record<string, unknown>, owner === undefined ? {} : { owner })
        if (c.expect === 'ok') {
          expect(verdict).toEqual({ ok: true })
        } else {
          expect(verdict.ok).toBe(false)
          const errors = verdict.ok ? [] : verdict.errors
          expect(errors.some((e) => e.includes(c.why as string)), `want ${c.why} in ${JSON.stringify(errors)}`).toBe(true)
        }
      })
    })
  }
})
