//! The RC1 conformance runner (test-only): judge a document against the generated RC1
//! contracts the way a client pre-check and a node's basic validation judge a create.
//!
//! The contracts are `forge-contracts/contracts/{forge-core,forge-collab,forge-community}.json`
//! (generated by `forge-contracts/schema/build.py`), parsed with full validation under protocol
//! 14 by the SDK's own rs-dpp (the `validation` + `json-conversion` features, switched on by the
//! dev-dependency). Each gets the id the deploy script derives (owner 0x07×32, nonce 1/2/3) and
//! the ids of the earlier contracts substituted for their placeholders, as
//! `tools/contract-validate` does.
//!
//! A document is judged by `validate_document_properties` with only its owner known
//! (0x07×32): the JSON schema, `maxBytes` and every `propertyConstraints` rule that reads no
//! total, time, height or other document. The rules that do (dense, c1..c6, lockGate,
//! platformChunks, oneLive, atMost20, notFuture, the `refersTo`/`ownerRefersTo`/`findBy` state
//! reads) are consensus's, covered by the live suite (`forge-contracts/scripts/rc1-live.mjs`).
//!
//! [`assert_valid`] / [`first_error`] are for builder tests: build a document's properties the
//! way the writer does and check RC1 accepts them. The vectors test runs every case in
//! `forge-contracts/vectors/rc1/`.

use std::collections::BTreeMap;
use std::sync::OnceLock;

use dpp::consensus::basic::BasicError;
use dpp::consensus::codes::ErrorWithCode;
use dpp::consensus::ConsensusError;
use dpp::data_contract::conversion::json::DataContractJsonConversionMethodsV0;
use dpp::data_contract::document_type::property_constraints::DocumentSystemValues;
use dpp::data_contract::validate_document::DataContractDocumentValidationMethodsV0;
use dpp::data_contract::DataContract;
use dpp::identifier::Identifier;
use dpp::platform_value::string_encoding::Encoding;
use dpp::platform_value::Value;
use dpp::version::PlatformVersion;
use serde_json::Value as Json;

use crate::layout::ForgeContract;
use crate::platform::FieldValue;

/// The protocol the RC1 contracts are registered under (Platform v4.2, protocol 14).
const PROTOCOL_VERSION: u32 = 14;

/// The signer and owner of every judged document, and the contracts' placeholder owner.
pub(crate) const OWNER: [u8; 32] = [7u8; 32];

/// The generated contracts, in registration order (a later one refers to the earlier ones).
const CONTRACTS: [ForgeContract; 3] = [
    ForgeContract::Core,
    ForgeContract::Collab,
    ForgeContract::Community,
];

fn root() -> &'static str {
    concat!(env!("CARGO_MANIFEST_DIR"), "/../../forge-contracts")
}

fn platform_version() -> &'static PlatformVersion {
    PlatformVersion::get(PROTOCOL_VERSION).expect("protocol 14 is known to rs-dpp")
}

/// `forge-core` -> `FORGE_CORE_CONTRACT_ID`.
fn placeholder_for(name: &str) -> String {
    format!("{}_CONTRACT_ID", name.to_uppercase().replace('-', "_"))
}

/// The three contracts, parsed once, indexed as [`CONTRACTS`].
fn contracts() -> &'static [DataContract; 3] {
    static PARSED: OnceLock<[DataContract; 3]> = OnceLock::new();
    PARSED.get_or_init(|| {
        let owner = Identifier::from(OWNER);
        let pv = platform_version();
        let mut placeholders: Vec<(String, String)> = Vec::new();
        CONTRACTS.map(|c| {
            let name = c.name();
            let path = format!("{}/contracts/{name}.json", root());
            let mut text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{path}: {e}"));
            for (placeholder, id) in &placeholders {
                text = text.replace(placeholder, id);
            }
            assert!(
                !text.contains("_CONTRACT_ID\""),
                "{name}: an id placeholder is left unresolved"
            );
            let mut json: Json = serde_json::from_str(&text).expect("contract JSON");
            let nonce = placeholders.len() as u64 + 1;
            let id = DataContract::generate_data_contract_id_v0(owner, nonce);
            json["id"] = Json::String(id.to_string(Encoding::Base58));
            json["ownerId"] = Json::String(owner.to_string(Encoding::Base58));
            let contract = DataContract::from_json(json, true, pv)
                .unwrap_or_else(|e| panic!("{name} fails full validation: {e}"));
            placeholders.push((placeholder_for(name), id.to_string(Encoding::Base58)));
            contract
        })
    })
}

fn contract_of(doc_type: &str) -> &'static DataContract {
    let c = ForgeContract::of(doc_type)
        .unwrap_or_else(|| panic!("`{doc_type}` is not an RC1 document type"));
    let i = CONTRACTS.iter().position(|x| *x == c).expect("listed");
    &contracts()[i]
}

/// A refusal's reason as the vectors name it: the JSON Schema keyword, the broken
/// `propertyConstraints` rule, `maxBytes`, or else the consensus error code (as b7gate's
/// `reason()`).
fn reason(e: &ConsensusError) -> String {
    match e {
        ConsensusError::BasicError(BasicError::JsonSchemaError(j)) => j.keyword().to_string(),
        ConsensusError::BasicError(BasicError::DocumentPropertyConstraintViolatedError(c)) => {
            c.constraint().to_string()
        }
        ConsensusError::BasicError(BasicError::DocumentPropertyMaxBytesExceededError(_)) => {
            "maxBytes".to_string()
        }
        other => other.code().to_string(),
    }
}

/// Judge `properties` as a create of `doc_type` by [`OWNER`]: `None` when RC1 accepts it, else
/// the first error as `(reason, message)`.
fn judge(doc_type: &str, properties: Value) -> Option<(String, String)> {
    let result = contract_of(doc_type)
        .validate_document_properties(
            doc_type,
            properties,
            &DocumentSystemValues::owned_by(Identifier::from(OWNER)),
            platform_version(),
        )
        .unwrap_or_else(|e| panic!("{doc_type}: validation could not run: {e}"));
    result.errors.first().map(|e| (reason(e), e.to_string()))
}

fn to_value(props: &BTreeMap<String, FieldValue>) -> Value {
    Value::Map(
        props
            .iter()
            .map(|(k, v)| (Value::Text(k.clone()), v.clone().into_value()))
            .collect(),
    )
}

/// The reason RC1 refuses these properties for a `doc_type` create by 0x07×32 (a schema
/// keyword, a `propertyConstraints` rule name, `maxBytes` or an error code), or `None` when it
/// accepts them.
pub(crate) fn first_error(doc_type: &str, props: &BTreeMap<String, FieldValue>) -> Option<String> {
    judge(doc_type, to_value(props)).map(|(why, _)| why)
}

/// Panic unless RC1 accepts these properties for a `doc_type` create by 0x07×32.
#[track_caller]
pub(crate) fn assert_valid(doc_type: &str, props: &BTreeMap<String, FieldValue>) {
    if let Some((why, message)) = judge(doc_type, to_value(props)) {
        panic!("RC1 refuses this {doc_type}: [{why}] {message}\n  properties: {props:?}");
    }
}

/// Panic unless RC1 refuses these properties for a `doc_type` create, first for `why`.
#[track_caller]
pub(crate) fn assert_refused(doc_type: &str, props: &BTreeMap<String, FieldValue>, why: &str) {
    match judge(doc_type, to_value(props)) {
        None => panic!("RC1 accepts this {doc_type}, want [{why}]\n  properties: {props:?}"),
        Some((got, message)) => assert_eq!(got, why, "{doc_type}: {message}"),
    }
}

#[cfg(test)]
mod vectors {
    use super::*;

    /// The committed vector sets and how many cases each holds
    /// (`forge-contracts/schema/vectors.py`). A change to either is a deliberate re-generation:
    /// update the counts here with it.
    const SETS: [(&str, usize); 3] = [
        ("forge-core", 159),
        ("forge-collab", 90),
        ("forge-community", 104),
    ];
    const TOTAL: usize = 353;

    /// Cases judged by the live suite only, never offline, by `(type, name)`.
    ///
    /// None: `vectors.py` keeps every rule that reads a total, time, height or another document
    /// (dense, c1..c6, lockGate, platformChunks, oneLive, atMost20, notFuture, the registration
    /// `where` checks, `refersTo`/`ownerRefersTo`/`findBy`) out of these sets and in
    /// `forge-contracts/scripts/rc1-live.mjs`, so every committed case is judged here. A case
    /// added to this list must name why.
    const LIVE_ONLY: [(&str, &str); 0] = [];

    /// A vector document: `{"$id": n}` is the 32-byte identifier filled with n and
    /// `{"$b": [fill, len]}` is `len` bytes of `fill` (b7gate's `to_value`).
    fn doc_value(j: &Json) -> Value {
        match j {
            Json::Object(m) if m.contains_key("$b") => {
                let a = m["$b"].as_array().expect("$b: [fill, len]");
                let fill = u8::try_from(a[0].as_u64().expect("fill")).expect("fill is a byte");
                let len = usize::try_from(a[1].as_u64().expect("len")).expect("len");
                Value::Bytes(vec![fill; len])
            }
            Json::Object(m) if m.contains_key("$id") => {
                let n = u8::try_from(m["$id"].as_u64().expect("$id: n")).expect("$id is a byte");
                Value::Identifier([n; 32])
            }
            Json::Object(m) => Value::Map(
                m.iter()
                    .map(|(k, v)| (Value::Text(k.clone()), doc_value(v)))
                    .collect(),
            ),
            Json::Array(a) => Value::Array(a.iter().map(doc_value).collect()),
            other => other.clone().into(),
        }
    }

    #[test]
    fn every_rc1_vector_is_judged_as_the_vectors_say() {
        let mut total = 0;
        let mut skipped = 0;
        let mut failures = Vec::new();
        for (set, want_count) in SETS {
            let path = format!("{}/vectors/rc1/{set}.json", root());
            let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{path}: {e}"));
            let cases: Vec<Json> = serde_json::from_str(&text).expect("vector JSON");
            assert_eq!(
                cases.len(),
                want_count,
                "{set}: the vector count changed; re-check the runner against the new set and \
                 update SETS"
            );
            total += cases.len();
            for c in &cases {
                let ty = c["type"].as_str().expect("type");
                let name = c["name"].as_str().expect("name");
                let expect = c["expect"].as_str().expect("expect");
                assert_eq!(
                    ForgeContract::of(ty).map(ForgeContract::name),
                    Some(set),
                    "{set}: `{name}` is a {ty}, held by another contract"
                );
                if LIVE_ONLY.contains(&(ty, name)) {
                    skipped += 1;
                    continue;
                }
                let got = judge(ty, doc_value(&c["doc"]));
                let verdict = match (expect, &got) {
                    ("ok", None) => None,
                    ("ok", Some((why, msg))) => {
                        Some(format!("accept wanted, refused [{why}] {msg}"))
                    }
                    ("refused", None) => Some("refusal wanted, accepted".to_string()),
                    ("refused", Some((why, msg))) => {
                        let want = c["why"].as_str().expect("a refused case names its why");
                        (why != want).then(|| format!("refused for [{why}], want [{want}]: {msg}"))
                    }
                    (other, _) => Some(format!("unknown expect `{other}`")),
                };
                if let Some(v) = verdict {
                    failures.push(format!("{set} / {ty} / {name}: {v}"));
                }
            }
        }
        assert_eq!(total, TOTAL, "the RC1 vector total changed");
        assert_eq!(
            skipped,
            LIVE_ONLY.len(),
            "a LIVE_ONLY case is not in the vectors"
        );
        assert!(
            failures.is_empty(),
            "{} of {TOTAL} RC1 vectors disagree:\n{}",
            failures.len(),
            failures.join("\n")
        );
    }

    #[test]
    fn the_helpers_judge_field_values() {
        let mut topic = BTreeMap::new();
        topic.insert("repoId".to_string(), FieldValue::Identifier([1; 32]));
        topic.insert("name".to_string(), FieldValue::text("web-dev"));
        topic.insert("vis".to_string(), FieldValue::text("public"));
        assert_valid("topic", &topic);
        assert_eq!(first_error("topic", &topic), None);
        topic.insert("vis".to_string(), FieldValue::text("private"));
        assert_refused("topic", &topic, "enum");
    }
}
